openshift/aws-account-operator

pkg/awsclient/client.go, pkg/controller/account/account_controller.go
This PR adds the ability to assume an AWS IAM role for new accounts created by the operator.
=> Add STS AssumeRole capability

pkg/awsclient/client.go, pkg/controller/account/account_controller.go
This pr has two commits. One fixes the formatting of the awsclient package. The second commit adds the main logic functions for account_controller.go. It also lets the operator be compiled and run without it creating an necessary resources. 
I also reorganized the functions in account_controller.go
=> Added main logic function to account_controller.go

pkg/controller/account/account_controller.go, pkg/controller/accountpool/accountpool_controller.go
This pr removes status from the account object creation. It also sets the accountpool as the owner of the account object. Lastly it adds error handling to the client.create call.
=> Account pool controller bug fixes

pkg/apis/aws/v1alpha1/accountpool_types.go
This PR adds 3 status fields to the AccountPool schema so that a user can easily see that status of claimed/unclaimed accounts and the desired pool size.
=> Add account status to AccountPool

pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/accountclaim_types.go, pkg/apis/aws/v1alpha1/accountpool_types.go, pkg/apis/aws/v1alpha1/register.go
The API types generated by the `kubebuilder` tool don't have some of the
things that are needed in order to automatically generate a client using
the Kubernetes code generation tools. In particular they don't have the
`+genclient` annotation. This patch adds these missing things.
=> Make API usable with the Go client generator

pkg/controller/accountpool/accountpool_controller.go
This PR removes the AWS account name from the AwsAccountID field in the Spec. This field should be filled in by the account controller with the numeric ID for the AWS account once its created.
=> This should be the AWS account ID numeric value

pkg/controller/account/account_controller.go
The PR ensure we paginate through all AWS accounts and finally that we check to see that we actually found and account or else return an error.
=> Paginate through accounts, return err if none found

pkg/awsclient/client.go, pkg/controller/account/account_controller.go
This PR ties the logic together in the reconcile function. It also refactors other functions used in the reconcile function.
The `NewClient()` from the `awsclient/client.go` file has been modified to include a token field. 
For now the initial aws credentials used are taken from the environment variables. 
```
"aws_access_key_id"
"aws_secret_access_key"
```
For creating accounts in testing comment line 172 out of the account pool controller and add this line
```
accountName := "EmailUserName-" + uuid
Example:
accountName := "razevedo-" + uuid
```
The following items are hard coded right now.
- IAM user name to be created is "osdManagedAdmin"
- email suffix "redhat.com"
- region "us-east-1"
The IAM user secrets are created in the namespace the operator is running in as "accountName-secret" …
=> Finished MVP logic for reconcile function

pkg/controller/accountpool/accountpool_controller.go
To ensure the account CRs don't get deleted, this PR adds a finalizer to them on creation
=> Add finalizer to the AWS Account objects

pkg/controller/account/account_controller.go
This PR uses the namespace from the request when looking for the secret containing the master AWS organization credentials
=> Update secret namespace to be from request

pkg/apis/aws/v1alpha1/accountclaim_types.go
The following [commit](https://github.com/openshift/aws-account-operator/commit/d648742fb15732b80a3f660523dd423c6028fbd0) causes the `kubernetes/gen-client` tool to break. 
This tag is crucial for UHC as it uses it to create internal clients and tools to watch and create `AccountClaim` CRD's. (Please be aware when moving it around..)
cc: @jharrington22 @jewzaam
=> Fix genclient tag

pkg/metrics/metrics.go
This PR creates various metrics to expose to Prometheus. 
- Total AWS Accounts in the Org (Implementation TODO)
- Total Account CRs created
- Number of Account CRs Unclaimed
- Number of Account CRs Claimed
- Number of Account CRs Failed
- Total Account Claim CRs
- The absolute value of the difference between the Pool Size and the number of unclaimed Account CRs
=> Create prometheus metrics

config/templates/aws-account-operator-csv-template.yaml
Fix missing `s` on the accountclaim CRD within the template.
=> AccountClaim crd name is plural

cmd/manager/main.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountpool/accountpool_controller.go, pkg/metrics/metrics.go
This PR uses the metrics package to expose the metrics endpoint on start of the operator, and updates the metrics  in their related contoller's reconcile loops.
=> Expose metrics when Operator start. Update metrics in respecitve reconcile loops

deploy/uhc_cluster_role.yaml, deploy/uhc_cluster_role_binding.yaml, deploy/uhc_service_account.yaml, hack/generate-operator-bundle.py
This PR creates a service account for UHC to consume and use, it will be deployed as part of the CSV.
=> Add service account aws-account-operator-client for UHC

pkg/apis/aws/v1alpha1/account_types.go, pkg/controller/account/account_controller.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountpool/accountpool_controller.go
The PR sets the pool and claim controllers to use a set namespace for creating and claiming accounts.
=> Set pool and claim controllers to use specific namespace for accounts

deploy/crds/aws_v1alpha1_accountpool_crd.yaml
The case of the JSONPath must match the field name in the CRD
=> Bug Fix: accountpool status now correctly shows counts when doing oc get

pkg/controller/accountclaim/accountclaim_controller.go
This PR fixes an issue where the AWS access key was being provided for both access key and secret access key.
=> Make sure we provide the AWS secret access key

pkg/controller/account/account_controller.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountpool/accountpool_controller.go
This PR refactors the accountclaim controller to exit the reconcile loop after each update to an object. It ensures the reconcile loop is idempotent.
=> One update an object once inside the reconcile loop

cmd/manager/main.go, deploy/prometheus-k8s-role.yaml, deploy/prometheus-k8s-rolebinding.yaml, pkg/metrics/service.go
This PR ensures that when the operator is deployed, all the proper objects are placed so prometheus can scrape the custom metrics.
-The operator creates an aws-account-operator service to expose the metrics over on deploy
-The operator creates an aws-account-operator servicemonitor to tell prometheus how to digest the metrics
-Removes the operator-sdk metrics service for now
-Includes a prometheus-k8s role for the aws-account-operator namespace that has permissions to get, list and watch services, pods and endpoints.
-Includes a prometheus-k8s rolebinding to allow the prometheus-k8s serviceaccount from the openshift-monitoring namespace to use the aformentioned role.
When the operator and the role/rolebindings are deployed, the aws-account-operator namespace must be given the following …
=> Deploy needed objects for prometheus metrics when the operator comes up

pkg/controller/account/account_controller.go
This pr sets a constant of awslimit which is an int where we will no longer create new accounts, but we will exit without updating the account state to "Failed". This make will mean that this account will still be counted as an unclaimedAccountCount and the accountpool controller will not create a new account. The next reconcile loop will just try to process this account again. 
This pr also adds better error handling for the aws call to create an account.
I moved the code below till after attempting to create an account. That way if we fail the account state has no been modified and we can try again. 
```
// set state creating if the account was able to create
setAccountClaimStatus(reqLogger, currentAcctInstance, "Attempting to create account", awsv1alpha1.AccountCreating, "Creating") …
```
=> Added account limit checking and better aws error handling

pkg/controller/account/account_controller.go, pkg/metrics/metrics.go
This PR adds aws metrics to the account controller and refactors the aws metrics call to not use the aws api where not needed.
=> Added aws metrics to account controller

pkg/controller/accountpool/accountpool_controller.go
This PR fixes a small info message typo in the account pool controller
=> Fix info msg typo

pkg/controller/account/account_controller.go
This PR bumps the operators hard AWS limit to 4700.
=> Bump operator hard AWS account limit

pkg/controller/account/account_controller.go
Per discussion with AWS, changing the support case severity to urgent. Since it wouldn't impact the resolution times and AWS was afraid the critical ones would cause problems in their end during the weekend
=> APPSRE-745 - Lower severity for support cases to urgent

cmd/manager/main.go
There is a bug in operator-custom-metrics that is not allowing the route to be updated https://github.com/openshift/operator-custom-metrics/issues/4
To get around that, this PR reverts the port number for the metrics endpoint to the previously used port number, which the current route already points to. There was no obvious reason to change this port number anyway. This does not fix the bug in the vendored code, but is just a work around.
=> Fix the port number so the route points to the right port

cmd/manager/main.go
Regisers ready metric with the metrics endpoint builder. This was overlooked when the metric was created. A future version of operator-custom-metrics will register a list of Collectors, so eventually this will no longer be an issue
=> Register Ready metric

pkg/controller/account/account_controller.go
Update service case request asking limit increases for multiple EC2 instance types:
- c5.xlarge 
- c5.2xlarge
- c5.4xlarge
- m5.xlarge (already in place today)
- m5.2xlarge
- m5.4xlarge
- r5.xlarge
- r5.2xlarge
- r5.4xlarge
=> SREP-1816 Increase limits multiple EC2 instance types

pkg/controller/account/account_controller.go, pkg/controller/account/ec2.go
This PR uses a go routine to initialize all supported regions by creating and terminating an EC2 instance in each region. Because we are using a go routine for each creation and monitoring its termination (or error) using a channel the creation of these resources will only take as long and the longest create/terminate action.
=> Initialize all regions with a EC2 instance

pkg/credentialwatcher/secretwatcher.go
We are unable to increase the `STSCredentialDuration` to over an hour until we update the roles maximum session duration. This change will require a larger amount of work, this gets the credentials working.
=> Reduce STS credential duration until we update roles

pkg/controller/account/account_controller.go
- Added a log before requeuing a support case check. 
- Increase interval between each check on a support case with the "PendingVerification" status to 10 minutes.
https://jira.coreos.com/browse/SREP-1883
=> SREP-1883 aws-account-operator increase support case check interval

pkg/localmetrics/localmetrics.go
Added legalID to as a label for the metric for available reused accounts. Instead of the total number of reused accounts available, the metric will now group the available accounts by their ID.
=> Modified Reuse metric to include ID

pkg/localmetrics/localmetrics.go
Reverts openshift/aws-account-operator#119 - This PR is causing the operator to crash, reverting until we have tested fix.
=> Revert "Modified Reuse metric to include ID"

pkg/awsclient/client.go
Extra checks to make sure that aws-acccount-operator code never uses a nil pointer. If a segfault still happens, then we can assume its coming from the aws library code.
=> SREP-1792: Add extra protections to aws client

pkg/controller/account/account_controller.go
Return if there is an error with creating an AWS client.
=> Add return statement

pkg/controller/accountclaim/accountclaim_controller.go
Fix for bug that was causing ci clusters to burn accounts, because their accountClaim was being created and deleted too fast (before an account could be assigned).
At the end of the finalizer block, there was a missing return, making the operator claim an account right after deleting the accountClaim, leaving an orphaned account behind.
=>  SREP-1950 - Fix for CI clusters burning accounts

pkg/localmetrics/localmetrics.go
Added legalID to reuse metric so that the number of available reused accounts are grouped by ID. Also fixed label issues that were causing problems in other PR. There is now a label for the LegalID in the metric itself, and the name label is just a const label in the metric definition.
=> New fix for adding LegalID to Reuse Metric

pkg/controller/account/account_controller.go
This PR bumps the AWS account limit, we'll be recycling some previous failed accounts this increase just unlocks the account controller.
=> Bump AWS account limit

hack/app_sre_create_image_catalog.sh
This PR adds the `--permissive` flag to the image registry docker build to ignore errors when loading and initializing the OLM bundles restoring the behavior the image registry initializer had before this PR https://github.com/operator-framework/operator-registry/pull/74
This option should be removed once https://github.com/operator-framework/operator-registry/pull/76 is merged which fixes the initial issue where the initalizer attempts to parse any file as JSON or YAML.
This should be considered temporary to fix our Jenkins builds until the above is complete.
=> Add permissive option to image registry initializer

pkg/controller/account/credentials_rotator.go
https://jira.coreos.com/browse/SREP-2034
The following error statement in account controller is not correctly formatted and has a typo
https://github.com/openshift/aws-account-operator/blob/master/pkg/controller/account/credentials_rotator.go#L65
=> Fix formatting and spelling

cmd/manager/main.go, pkg/controller/account/account_controller.go, pkg/localmetrics/localmetrics.go
Added Go routine in main.go to update the total number of AWS account every hour. Moved logic of updating this number to local metrics file so that total number is calculated in local metrics. The API call still needs to be tested however
=> Created Go Routine to update total AWS Accounts every N hours

deploy/cluster_role.yaml
I don't think this is required, but being explicit with RBAC is probably a safer bet.
=> Explicitly support * on accountpools

deploy/cluster_role_binding.yaml
Since the operator and therefore the service account is always in the `aws-account-operator` namespace by convention, I want to make this explicit as its the only bit that needs replacing when deploying the operator.
=> Explicitly call out namespace in clusterrolebinding

deploy/crds/aws_v1alpha1_account_crd.yaml, deploy/crds/aws_v1alpha1_accountclaim_crd.yaml, deploy/crds/aws_v1alpha1_accountpool_crd.yaml, pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/accountclaim_types.go, pkg/apis/aws/v1alpha1/accountpool_types.go
The subresouces section of the CRDs were removed after a regen in this commit:
https://github.com/openshift/aws-account-operator/commit/a7f123f83ceb78bff2a7441add844c56fbb8821e#diff-85bc3ddf6b56ff3826c09f368b0f6293
However, this removal causes bugs in the operator. A similar issue was found here: https://github.com/kubernetes-sigs/kubebuilder/issues/751
What likely happened was operator-sdk enabled that option (`+kubebuilder:subresource:status`) behind the scenes before but with a new updated disabled it. So when the CRDs were generated with a newer version, the subresources field was removed. The fix is to explicitly add that option to the CRD types in Go and regenerate the CRDs
=> Fix removal of subresouces in CRD

pkg/controller/account/account_controller.go, pkg/localmetrics/localmetrics.go
The aws-account-operator total number of AWS account metric is showing 0 occasionally, I suspect this is due to the API returning the "TooManyRequestsException" error (which we've experienced before) and then returning 0
Maybe we want to parse the returning API error?
https://github.com/openshift/aws-account-operator/blob/master/pkg/controller/account/account_controller.go#L820
This only merged in staging, we want to resolve this before our next prod push
https://jira.coreos.com/browse/SREP-2108
Along with this, I updated the other error handing case in metrics.
=> Handle and log errors in localmetrics

deploy/uhc_cluster_role.yaml
As part of OCM migration to `controller-runtime`, we need to have permissions to create events and create and get configmaps. This is done only in a dedicated namespaces called `uhc-leadership`.
=> add permissions to uhc-cluster-role

pkg/controller/account/account_controller.go
Support cases are erroring due to the lack of a language. This adds a language to the cases and a configurable case variable.
=> Add language to created AWS Case

deploy/crds/aws_v1alpha1_account_crd.yaml, pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Currently, an account CR only has a reference to the name of an accountClaim. However, these names are not unique. In order to ensure the Account knows the accountClaim its linked to, the namespace of the accountClaim should also be referenced in its spec.
=> Add claimLinkNamespace field to Account CR

cmd/manager/main.go, pkg/controller/account/account_controller.go, pkg/controller/utils/conditions.go, pkg/localmetrics/localmetrics.go, pkg/totalaccountwatcher/totalaccountwatcher.go, pkg/totalaccountwatcher/totalaccountwatcher_test.go
https://jira.coreos.com/browse/SREP-2163
Currently the aws-account-operator will check the total number of created accounts when an account CR has `.status.state` as "" and `.status.claimed` as false.
We should do this independently of the reconcile loop and run it on a timer since we consistently hit API errors from AWS blocking the controller as well as blocking the refreshing of already created accounts. We would do this similar to the way we're updating the localmetics in main.go.
The problem is that we need to check this against the awsLimit var so that we don't create too many accounts. Should we create an internal counter too that is refreshed on every update from AWS?
Done criteria:
- Checking of total number of AWS accounts is done outside the loop
- We need to observe awsLimit …
=> Move check for awslimit outside of reconcile.

pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/reuse.go, pkg/controller/accountpool/accountpool_controller.go, pkg/controller/accountpool/accountpool_controller_test.go, pkg/controller/utils/utils.go
The AccountClaim controller will be given an AWS Account ID from OCM which it will then create an Account CR. The AccountClaim controller will then wait for this CR to be reconciled by the Account controller which will set the Account CR status to "Ready"
=> Implement BYOC AccountClaim logic

pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
At least one of the fields need to NOT be empty for CR to reconcile.
If both are empty then exit with nil.
=> Add check for AWSCustomPolicy and AWSManagedPolicies

pkg/awsclient/client.go, pkg/awsclient/mock/mock_client.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Right now, the controller blindly tries to `Create` both IAM Roles and Policies. However, if they already exist in the AWS account, and the CR has been updated with new permissions, they will not be applied as the `Create` will fail with `EntityAlreadyExists`. This PR adds `CreateOrUpdate` logic to delete and recreate Roles and Policies when they already exist in an AWS account to ensure they are always up to date.
=> CreateOrUpdate logic for Self-service IAM Roles and Policies

pkg/controller/account/account_controller.go, pkg/controller/account/ec2.go
Currently, `InitializeSupportedRegions` take a set of credentials returned from `StsAssumeRole`. These creds go on to be used to build an AWS client in `InitializeRegion`. However, these credentials are already used to create an AWS Client before `InitializeSupportedRegions` is called. To make the function more flexible and to reduce complexity, this PR changes `InitializeSupportedRegions` to take an AWS client instead.
=> InitializeSupportedRegions takes an AWS Client instead of a set of credentials

pkg/controller/accountclaim/accountclaim_controller.go
Legal Identity needs to be added to the account spec from the accountclaim for BYOC accounts
=> Copy LegalID from claim to account for BYOC

pkg/controller/account/account_controller.go, pkg/controller/account/iam.go
`getStsCredentials` has an `iamRoleName` parameter but is unused. This PR leverage this to enable arbitrary roles for `getStsCredentials` and `BuildSTSUser`
=> Support arbitrary role in getStsCredentials and BuildSTSUser

pkg/controller/account/account_controller.go
Currently CreateIAMUser will return an error even it succeeds in creating a new user. This commit changes CreateIAMUser to handle the case of a new account properly.
=> CreateIAMUser fix

pkg/controller/account/account_controller.go, pkg/controller/account/ec2.go
Reverts openshift/aws-account-operator#192
This PR is being reverted as it introduced an error when initializing accounts.
We create a new AWS client within the `InitializeRegion` function because we need to connect to the specific region to use the AMI and start/terminate the AWS EC2 instance.
Error from the account_controller:
`{"level":"error","ts":1573654676.9214592,"logger":"controller_account","msg":"Failed while trying to create EC2 instance,\n\t\t\t\tAWS Error 
Code: InvalidAMIID.NotFound, \n\t\t\t\tAWS Error Message: The image id '[ami-04642fc8fca1e8e67]' does not exist","Request.Namespace":"aws-acc
ount-operator","Request.Name":"osd-creds-mgmt-vrb5t7","error":"InvalidAMIID.NotFound: The image id '[ami-04642fc8fca1e8e67]' does not exist`
=> Revert "InitializeSupportedRegions takes an AWS Client instead of a set of credentials"

pkg/apis/aws/v1alpha1/account_types.go, pkg/controller/account/account_controller.go, pkg/controller/account/credentials_rotator.go
This PR fixes a missing role name when calling `getStsCredentials` in the credential rotation file. I moved the const to the API types file so it could be used in the secret watcher.
=> Add missing role name to credentials rotator

deploy/crds/aws_v1alpha1_account_crd.yaml, pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go, pkg/controller/account/account_controller.go, pkg/controller/account/credentials_rotator.go, pkg/controller/account/ec2.go, pkg/controller/account/iam.go, pkg/credentialwatcher/secretwatcher.go
This PR fixes an issue where AWS console URLs are only valid for 15 minutes after creation regardless of the AWS STS session duration.
To fix this we a few things differently:
1. Remove the AWS console URL from the sre-credentials secret and rename the original secret <account-name>-sre-cli-credentials
2. Create a new secret called <account-name>-sre-console-credentials
3. We generate a new AWS console URL every 15 minutes based on the sre-console-secret creation time
This also fixes a bug where the CLI credentials could become expired.
=> Refresh web console signin token

pkg/controller/account/ec2.go
https://jira.coreos.com/browse/SREP-2154
Currently initialization of regions may fail due to multiple instance since the specific instanceId is not checked.
=> Initialization of region verification checks unique instance

deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_cr.yaml, deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml, pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
https://jira.coreos.com/browse/SREP-2328
Formerly the AssumeRolePolicyDocument took an AWS-ID and defaulted to the root user. This PR changes the AWS-ID to an ARN.
=> Change AWS Id to  AWS arn

pkg/controller/utils/conditions.go
This PR fixes an issue where the `status.conditions[].lastTransitionTime` is `null` due to a CRD change here #129 
This should set the lastTransitionTime to LastProbeTime if its not of type `metav1.Time`
=> Ensure we have a timestamp as lastTransitionTime

pkg/controller/account/account_controller.go, pkg/controller/utils/conditions.go
In this PR we are explicitly checking `status.conditions[].LastTransitionTime` to see if its an empty struct and update it to `LastProbeTime`
=> Explicitly check conditions LastTransitionTime

pkg/controller/utils/conditions.go
Reverts openshift/aws-account-operator#206
No longer required with #207
=> Revert "Ensure we have a timestamp as lastTransitionTime"

pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/iam.go
Account Controller BYOC Logic
1. Skip creating the AWS account
2. Create new IAM access key for root credentials
3. Delete console login (??)
4. Delete original root IAM access keys that were provided
5. Assume user in this account using new root credentials (I think this and 6 are the same)
6. Following existing account setup logic
7. Skip creating support tickets for limit and enterprise support logic
8. Update status and conditions
=> Implement BYOC Account controller logic

pkg/controller/utils/utils.go
`ClaimLinkNamespace` should be set to blank when a new account CR is generated by the AccountPool.
=> Set ClaimLinkNamespace when Creating an Account CR

deploy/crds/aws_v1alpha1_account_crd.yaml, pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go
This CR sets `.spec.legalEntity` to omitempty again.
=> Make legalEntity optional again

hack/generate-operator-bundle.py
CRD's in the CSV are required to have a description. Using the kind name for the moment until we figure out how to populate the description.
=> CSV require a description for CRDs

pkg/controller/account/byoc.go
This PR ensures that if the BYOC AWS client does not get initialized correctly, the error is returned.
=> Handle error for BYOC aws client setup

deploy/uhc_cluster_role_binding.yaml
This PR is an attempt to solve https://jira.coreos.com/browse/APPSRE-961.
The plan is to add OCM developers to this group on the integration environment only.
Please let me know what you think.
=> add aws-account-operator-client Group to ClusterRoleBinding

pkg/controller/account/account_controller.go, pkg/controller/utils/conditions.go
This PR removes a fix that was put in place to specifically fix `.status.conditions[].lastTransitionTime` this has been merged to prod and all accounts reconciled.
cc/ @wshearn @fahlmant
=> Remove conditions check for invalid lasttransitiontime

hack/olm-registry/olm-artifacts-template.yaml
This PR adds the clusterrolebinding for the aws-acconut-operator-client ServiceAccount to the oc template that is applied on deployment.
Currently that template is not generated automatically as part of the deployment and probably should be if we are going to include things such as this clusterrolebinding. At the moment I don't see an easier way to apply the additional subject to the clusterrolebinding which is managed by OLM and at this time OLM does not support modifying or customizing the ciusterrolebinding it creates for service accounts listed in the CSV.
This clusterrolebinding is not going to have the same name as the one created by OLM but that shouldn't be an issue for the moment.
cc/ @maorfr @jewzaam @rogbas
=> Add clusterrolebinding to oc template

pkg/controller/account/account_controller.go, pkg/controller/account/credentials_rotator.go, pkg/controller/account/iam.go, pkg/controller/accountclaim/accountclaim_controller.go
This PR fixes a few bugs with BYOC and also attempts to handle inconsistencies of the AWS API when working with STS tokens
There are two main problems its fixing:
- The AccountClaims status was never updated to Ready (For a few reasons)
- The AWS API seems to be returning "InvalidClientTokenId" or "AccessDenied" inconsistently with the STS tokens, I've implemented some retries.
=> Ensure we update the status on the accountclaim

pkg/controller/account/account_controller.go
Adds a comment to exported variable AwsLimit to conform with Go linting best practices.
Also removes a single trailing white space.
=> Comments AwsLimit variable to conform with Go linting best practices

pkg/controller/accountclaim/accountclaim_controller.go
This PR ensures the finalizer for the accountClaim is removed for BYOC accountClaims when the accountClaim is deleted.
=> Remove finalizer if BYOC

pkg/apis/aws/v1alpha1/account_types.go, pkg/controller/account/account_controller.go, pkg/controller/accountpool/accountpool_controller.go
Currently when an accountClaim CR is deleted and the AccountClaim was BYOC it will attempt to delete the Account CR because the accountClaim is set as an owner reference. This will fail because the finalizer on the account CR is never removed.
It fixes this error where we attempt to get the `.Spec.claimLink` in the reconcile loop instead of deleting the account and exiting the reconcile.
`"level":"error","ts":1576783019.8541033,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"account-controller","request":"aws-account-operator/osd-creds-mgmt-vqnml2","error":"AccountClaim.aws.managed.openshift.io \"jamesh-corp\" not found"`
=> Remove finalizer from the Account CR if BYOC

deploy/crds/aws_v1alpha1_awsfederatedrole_crd.yaml, pkg/apis/aws/v1alpha1/awsfederatedrole_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go
OCM requires a way to dynamically display a user friendly role name, along with the description we've added a display name to the spec.
=> Add roleDisplayName for OCM user interface

pkg/credentialwatcher/secretwatcher.go
Currently if there's an error when getting the associated account during a secret watch, the code continues and tries to use the secret, resulting in a segfault. Adding a return out of the function solves this issue.
=> Return when account can't be found by secretwatcher to prevent segfault

.gitignore, pkg/controller/accountclaim/reuse.go
This PR adds Boolean rotateConsoleCredentials and RotateCredentials to true after account clean up so that credentials are refreshed when doing an account reuse.
=> Added credential refresh to reuse

.gitignore, cmd/manager/main.go, pkg/controller/account/account_controller.go, pkg/controller/account/credentials_rotator.go, pkg/credentialwatcher/secretwatcher.go
This PR updates the RotateConsoleCredentials and RotateCredentials functions so that they pull that lastest account CR data before updating.
=> Rotate credentials by accounts that are in Ready state

pkg/awsclient/client.go, pkg/awsclient/mock/mock_client.go, pkg/controller/account/account_controller.go, pkg/controller/account/account_controller_test.go, pkg/controller/account/byoc.go
Checks for the existence of the BYOC AdminAccess role before attempting to
create it.  If it exists (ie: the returned struct is not empty), then lists
the attached role policies, and detaches them, and then deletes the role.
(The role cannot be deleted with attached policies.)
After deleting the role, the contoller then continues to create the role fresh.
REF: [OSD-2582](https://issues.redhat.com/browse/OSD-2582)
=> Deletes BYOCAdminAccess role and recreate if it exists

pkg/controller/account/credentials_rotator.go
Fixes a bug where the awsclient is a nil pointer and causing  panics.
=> Added missing return

pkg/apis/aws/v1alpha1/accountclaim_types.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/utils/conditions.go
This PR prevents a BYOC customer from installing multiple clusters in a single AWS account
=> BYOC does not supporting multiple clusters

pkg/controller/account/account_controller.go, pkg/controller/account/cases.go
This PR moves functions for AWS support cases-related code to their own file.  This is the first of several to reduce the length and complexity of the accounts_controller.go file.
REF: [OSD-1937 "aws-account-operator breakout functions from account_controller.go"](https://issues.redhat.com/browse/OSD-1937)
=> Removes support cases functions to own file

deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml, pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
* Updates AwsFederatedAccountAccess status to include the consoleURL for
role assumption by provided account id
* Changes createOrUpdateIAMRole to return the role, so the ID can be used 
to construct the consoleURL
REF: [OSD-2710](https://issues.redhat.com/browse/OSD-2710)
This has been tested locally with the operator-sdk and appears to work as expected.
=> Adds consoleURL to AwsFederatedAccountAccess status

pkg/controller/account/account_controller.go
Reverts openshift/aws-account-operator#266
There are enough accounts provisioned, we just need reset some.
=> Revert "Update account_controller.go"

pkg/controller/account/account_controller.go
This PR should stop the account controller from submitting Support tickets if the account has already be "Ready" in the past. This helps when resetting accounts.
=> Only set PendingVerification if the account is new

deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml, pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Sets `omitempty` for the CosoleURL string in the AWSFederatedAccountAccessStatus struct in
awsfederatedaccountaccess_types.go.
=> Makes the consoleURL field in AWSFederatedAccountAccessStatus optional

pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, pkg/controller/utils/utils.go
When an AWSFederatedAccountAccess CR is deleted, the federated role needs to be cleaned up by detaching all policies from it and then deleting the role.
=> Add finalizer and handling for AWS Federated Account Access

pkg/controller/account/account_controller.go
Currently resetting accounts is not working due to a short time out. This is a hotfix to get accounts reuse working again.
=> Increase creation timeout

hack/scripts/reset_account_cr.sh
This script resets an account CR so that it can be reused. It does not reset the `.spec.legalEntity` id on purpose so that this account will only be reused by the same `.spec.legalEnity.Id`
=> Adding script to reset account CR

pkg/controller/accountclaim/reuse.go
This commit reverts #246, 5fab2a348bf6a687af331c204bb82d3384b71d06,
"Added credential refresh to reuse", to address multiple reconcile
attempts on the account.  This addresses the failed accounts created
by the account reuse, [OSD-2800](https://issues.redhat.com/browse/OSD-2800).
=> Revert 246 "Added credential refresh to reuse" 

pkg/controller/accountclaim/accountclaim_controller_test.go
The accountclaim controller needs tests. This is a simple placeholder test to be changed as more PRs change the accountclaim controller.
=> Create accountclaim test file

pkg/controller/accountclaim/reuse.go
https://github.com/openshift/aws-account-operator/pull/277 reverted
credential refreshes from the account reuse as part of the
mitigation of OSD-2800.
This commit moves the credential refresh to `resetAccountSpecStatus`,
to take advantage of the existing status update there, and ensuring
a status update occurs just once, reducing the chance of conflict
with other updates.
REF: [OSD-2827](https://issues.redhat.com/browse/OSD-2827)
=> Reintroduce credential refresh to account reuse

deploy/crds/aws_v1alpha1_awsfederatedrole_customeradmin_cr.yaml, deploy/crds/aws_v1alpha1_awsfederatedrole_readonly_cr.yaml
Both our defined Federated Roles are missing the roleDisplayName needed to apply them.
=> Update Federated Role CRs to include roleDisplayName

Makefile, hack/templates/aws_v1alpha1_account.tmpl, hack/templates/aws_v1alpha1_awsfederatedaccountaccess_cr.tmpl
This PR creates make targets to test federated account access.
You need to define the following environment variables:
`export OSD_STAGING_1_AWS_ACCOUNT_ID=<AWS Account ID>`
`export OSD_STAGING_2_AWS_ACCOUNT_ID=<AWS Account ID>`
You'll need to make sure your AWS IAM user in OSD staging 2 has the following permissionion:
```
{
"Effect": "Allow",
"Action": "sts:AssumeRole",
"Resource": "arn:aws:iam::*:role/*"
}
```
Then:
Running `make test-awsfederatedaccountaccess` will test creating and deleting the following:
1. Create AWS Account
2. Create AWS Federated Role
3. Create AWS Federated Account Access with IAM User ARN from OSD staging 2
4. Test Assume role using your IAM user in OSD staging 2
5. Delete AWS Federated Account Access
6. Delete AWS Federated Role
7. Delete AWS Account and …
=> Create make targets for testing Federated Access

pkg/controller/awsfederatedrole/awsfederatedrole_controller.go, pkg/controller/awsfederatedrole/finalizer.go
This PR adds a finalizer to all Federated Roles that don't have it, as well as handles cleanup during deletion of the Role. If the Federated Role is referenced by a Federated Account Access, then the Federated Account Access is deleted, which triggers its own finalizer cleanup.
=> Ensure finalizer is added and handled for AWS Federated Roles

pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Currently, if there is an error creating the role, and the error is an AWS API error (awserr.Error), only "EntityAlreadyExists" is handled, and all other errors are slilently dropped on the floor.  This adds an `else` case to return the awserr.Error.Code() string as an error if it isn't the EntityAlreadyExists error.
REF: panics[1] due to role being nil, ultimately tracked down to unhandled "MalformedPolicyDocument" errors returned by AWS that were being ignored by the code.
[1] https://github.com/openshift/aws-account-operator/pull/300#pullrequestreview-369920242
=> Adds handling of unexpected AWS API errors

cmd/manager/main.go, pkg/credentialwatcher/secretwatcher.go
This PR should change secretwatcher to only rotate STS credentials if the Account CR is in a Ready state.
I'm also reducing the scan interval to 1 minute so that we're renewing less secrets on every run.
=> Only rotate STS credentials when Account CR state is Ready

pkg/controller/account/account_controller.go, pkg/controller/account/cases.go
1. Moves constants still in use to cases.go
2. Removes constant "caseDesiredInstanceLimit" - no longer used
3. Removes slice variable "coveredInstanceTypes" - not referenced in codebase
REF: [OSD-2870](https://issues.redhat.com/browse/OSD-2870): Remove code related to AWS Limit increase support ticket.
=> Removes support ticket related code from account_controller.go

pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/reuse.go
Cross namespace ownership is disallowed by kubernetes by design.
From https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection
"Note: Cross-namespace owner references are disallowed by design. This means: 1) Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped. 2) Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners."
In one case, an Account CR was garbage collected while having an active cluster and accountclaim.
To fix this
1) The owner reference is removed when creating a BYOC Account CR
2) The AccountClaim finalizer code now does a Delete on the Account CR if the account is BYOC
=> Remove owner reference for BYOC accounts from creating accountclaim

pkg/awsclient/client.go, pkg/awsclient/mock/mock_client.go, pkg/controller/accountclaim/reuse.go
This PR cleans up route53 hosted zones during the reuse cleanup code. A hosted zone can only be deleted if all record sets, except for the SOA and NS records, are deleted. Certman operator uses TXT records for certificate setup, so included in this cleanup is the deletion of TXT records within the hosted zone before the deletion is called.
=> Implement Route53 hosted zone cleanup for reuse

Makefile
This adds the ability to retrieve the FAA Role UID and use it for the `test-switch-role` target, automating that step where it was previously a manual step.
=> Handle the new UID assignment to FAA Roles in the Makefile tests

pkg/apis/aws/v1alpha1/accountclaim_types.go, pkg/controller/accountclaim/accountclaim_controller.go
Moved the Account CR base case handler bellow AccountReady and AccountFailed tests, the base case was being checked too early causing the AccountFailed test never being reached. https://issues.redhat.com/browse/OSD-2627
=> Fix for AccountClaim not registering Account CR being in an error state

pkg/apis/aws/v1alpha1/shared_types.go, pkg/controller/account/account_controller.go, pkg/controller/account/cases.go, pkg/controller/account/ec2.go, pkg/controller/account/iam.go
Ticket: https://issues.redhat.com/browse/OSD-2835
Create pkg/apis/aws/v1alpha1/shared_types.go add constants and types that could shared in the package v1alpha1
https://github.com/openshift/aws-account-operator/blob/master/pkg/controller/account/account_controller.go#L79-L138
Done criteria:
- Move types and constants that are shared between APIs to this file
- Any constants that we can reference here to keep controller files clean
Testing:
- To test you just need to apply  an account CR and check that it becomes ready without issues.
Edit: Description
=> Move constants and types that could shared in the package v1alpha1

pkg/controller/utils/conditions.go
This fixes a bug that prevents subsequent occurances of an account condition from updating the `lastProbeTime` field, which would hide subesequent occurances of the same condition.
REF: https://issues.redhat.com/browse/OSD-3252
To Test:
Edit account_controller.go, and add:
```go
SetAccountStatus(reqLogger, currentAcctInstance, "Making A Fake Status Failure", awsv1alpha1.AccountFailed, AccountFailed)
err = r.Client.Status().Update(context.TODO(), currentAcctInstance)
if err != nil {
return reconcile.Result{}, err
}
```
... to the reconcile loop after fetching the `currentAcctInstance` and it's error handling.  Your code should go in around line 238.
Then, start the operator locally:
```sh
FORCE_DEV_MODE=local operator-sdk up local --namespace=aws-account-operator
```
And try to run the …
=> Fixes new condition occurances timestamps failing to update

Makefile, README.md, hack/files/aws_v1alpha1_zero_size_accountpool.yaml, hack/templates/aws_v1alpha1_aws_account_operator_credentials.tmpl
This change adds a deploy target to the Makefile, to automate the install
of the aws-account-operator pieces required for operation.
`make deploy` will create the operator secret, deploy the CRDs, and create an accountPool with zero size.  It's also idempotent, so it can be run multiple times with no issue and will just replace the resources that differ from what it expects (in case you create a bad secret, or whatnot).
REF: [https://issues.redhat.com/browse/OSD-3077](https://issues.redhat.com/browse/OSD-3077)
=> Adds deploy target for automating install of the aws-account-operator

hack/scripts/aws/rotate_iam_access_keys.sh
This PR fixes a bug where the IAM_USER var isn't set if the IAM user didn't exist and is created by the script before the access keys are created/rotated.
=> Set IAM_USER var to create access keys

Makefile
This PR adds a make target that should run the following tests/targets
- CCS
- Reuse
- Account Creation
- Federated Access
=> Add test-all make target

hack/templates/aws_v1alpha1_ccs_accountclaim_cr.tmpl
This PR removes the duplicate "name" field from the awsCredentialSecret in the CCS accountClaim CR template.
It also removes trailing whitespaces from lines.
Tested with the `make test-ccs` target with no issues.
=> Removes duplicate "name" field from awsCredentialSecret; trailing whitespaces

deploy/crds/aws_v1alpha1_account_cr.yaml, deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_cr.yaml
This PR takes out specific user information from the AWS Federated Account Access example CR, as well as fills out a basic spec for the Account example CR.
=> Fix example CRs for Account and FederatedAccountAccess

hack/scripts/aws/rotate_iam_access_keys.sh
The PR ensures no newline character is added to the IAM user credentials secrets for tests.
=> Don't return newline char

pkg/apis/aws/v1alpha1/shared_types.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Currently, there is no direct reference to the target AWS account for an AWS Federated Account Access. Instead, it relies on using the `aws` secret in the namespace of the accountclaim to call `aws sts get-caller-identity`. This causes an issue if the aws secret is deleted before the finalizer code is run.
This PR fixes this by adding a label to the CR with the account ID. It still relies on the secret to get the account ID, but only needs to happen once. From then on, the ID can be referenced in the CR by the label. 
This also includes a new function to check an arbitrary label on the CR, rather than just the `uid` label.
=> Add label for the target awsAccountID where the role is created

pkg/apis/aws/v1alpha1/shared_types.go, pkg/awsclient/tags.go
This PR implements a tag builder to the awsclient currently it would support EC2 and IAM tags
=> Add tag builder to client

pkg/apis/aws/v1alpha1/shared_types.go, pkg/awsclient/tags.go
This PR makes changes to the tag builder to take an Account CR. It includes claimLink and claimLinkNamespace which will be blank if they don't exist. Ideally in the future we'll move user creation to when the accountClaim is triggered filling in this field. These fields are populated for CCS. 
Remove keeping state and make this function initialize everytime to ensure we don't hold stale data.
=> Update tag builder to take account claim, initialize every time

pkg/credentialwatcher/secretwatcher.go
Since this log message is logging twice, let's just remove it because it's not really adding much value since the account isn't ready anyway, and with failed accounts this is just causing a bunch of noise in the logs.
=> Fix Double Logging for Secrets Refresh

pkg/credentialwatcher/secretwatcher.go
This PR ensures the credential watcher is only updating the Account CR status object if the credentials bool its updating is false.
=> Update rotate credentials bool only if false

hack/scripts/aws/rotate_iam_access_keys.sh
This PR removes erroneously added output redirection to stderr on several lines where variables are set. This fixes syntax errors in the editor and is good practice, but will not change functionality at all.
=> Removes erroneous redirection to stderr in rotate_iam_access_keys.sh

pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/iam.go, pkg/controller/utils/utils.go
This PR is a first pass at refactoring the BuildIAMUser function. It removes the logger from outer functions where possible and cleans up the logic within the function by moving out as much as possible into smaller functions. A couple of TODO's but this makes it much easier to read.
I think that we should move the logger completely from BuildIAMUser and return any errors out to the reconcile and parse there. I didn't do that here because of 1. time and 2. PR size.
All errors are returned to the reconcile function which will then fail the account if there is a problem.
`make test-all` is passing locally and I've verified that the AWS credentials are working.
=> Refactor BuildIAMUser

pkg/controller/account/iam.go
Fixes the keys that were changed during a refactor. Since credentialWatcher isn't using the same logic as this when the keys are first rotated they're fixed and every subsequent rotation fixes them as well.  This fixes that issue so they're also correct the first time.
=> Fixes keys that were changed during refactoring.

pkg/controller/account/iam.go
745ef75 Enables the CreateIAMUser the possibilty to return a null
pointer even when the IAM user is successfully created. It appears that
the for loop was not returned in the correct position.
=> CreateIAMUser panic resolution

pkg/controller/account/account_controller.go
The PR removes the osdCcsAdmin key rotation from the BYOC workflow
=> Remove osdCcsAdmin AWS key rotation

pkg/controller/accountclaim/reuse.go
CCS IAM clean up isn't using the correct tag names to search and delete users.
=> Use shared types key name vars

deploy/operator.yaml
Fixes the typo that's preventing the operator from deploying.
=> Fix Typo for memory limit

pkg/apis/aws/v1alpha1/shared_types.go, pkg/controller/account/account_controller.go, pkg/controller/account/ec2.go
The operator should tag AWS resources (eg. EC2 instances) it creates so it can ensure during the clean up process that it deletes any instances that might have been left over during account initialization.
Ticket: https://issues.redhat.com/browse/OSD-3312
Test:
- I simply created an account which should test the creation and termination of ec2 instances
Currently this change tags the instances we start on account [creation](https://github.com/openshift/aws-account-operator/blob/master/pkg/controller/account/account_controller.go#L470). I would like some insight into other resources we should be tagging.
=> Tag EC2 instances

pkg/controller/account/iam.go, pkg/controller/accountclaim/reuse.go, pkg/controller/utils/utils.go
https://issues.redhat.com/browse/OSD-2875
During reuse, any current access key should be revoked and all associated secrets removed. 
WIP: When should the credentials and secrets be recreated? During the reuse code, when an account is claimed, or should we eliminate at least the two IAM user credentials secrets completely?
=> Cleanup secrets and access keys on reuse

pkg/controller/account/credentials_rotator.go
This PR adds secret owner refs during a refresh as well as during the initial creation.
To Test:
* Start on the master branch.
* `operator-sdk up local --namepsace aws-account-operator`
* `make create-account`
* Wait one hour and then ensure that both `osd-creds-mgmt-osd-staging-1-sre-console-url` and `osd-creds-mgmt-osd-staging-1-sre-cli-credentials` are both refreshed (secret age will be less than 1 hour)
* `oc get secret -n aws-account-operator osd-creds-mgmt-osd-staging-1-sre-console-url -o json` as well as `-sre-cli-credentials` and see that there is no longer an owner reference.
* checkout this PR
* `operator-sdk up local --namespace aws-account-operator`
* Wait another hour, and ensure that both of the secrets above have refreshed again.
* `oc get secret -o json` for both secrets …
=> Adds secret owner refs during refresh.

pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/byoc_test.go
This moves the BYOC initialization and logic from the account_controller.go file to byoc.go via a new `initializeNewBYOCAccount` function.  This has been tested locally and is working as expected.
This depends on PR #295 and should not be merged before that.
REF: [https://issues.redhat.com/browse/OSD-2833](https://issues.redhat.com/browse/OSD-2833)
=> Separates BYOC Logic from account_controller.go

pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/accountclaim_finalizer.go, pkg/controller/accountclaim/reuse.go
Currently, the byoc secret can be deleted before the accountclaim has a chance to finalize. This PR adds a finalizer to the byoc secret to ensure the secret is still around when the accountclaim tries to use it. Once the claim has used the secret, it removes the finalizer.
=> Add finalizer to the byoc secret, ensure it can be used before deletion

pkg/controller/account/account_controller.go
Refact account controller to use awsClientBuilder when building awsClients.
Ticket: https://issues.redhat.com/browse/OSD-2839
Test:
- Created an account
=> Refactor awsClient

pkg/controller/account/account_controller.go, pkg/controller/account/account_controller_test.go
This PR sets the account controller to log and ignore accounts with the `.status.state` "Failed"
=> Log failed accounts and don't reconcile

cmd/manager/main.go, pkg/localmetrics/localmetrics.go, pkg/totalaccountwatcher/totalaccountwatcher.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
`name=aws-account-operator` can just be a const label. It is not necessary to use a `GaugeVec` in this case.
=> Add const label name to metrics

pkg/apis/aws/v1alpha1/shared_types.go, pkg/controller/account/account_controller.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/organizational_units.go, pkg/controller/accountclaim/organizational_units_test.go
[ticket](https://issues.redhat.com/browse/OSD-3924)
Remove hard coded account limit from the operator. Since different environments have different account limits we should look for the given limit in the operator's ConfigMap.
=> Use configmap to determine aws account limit

cmd/manager/main.go, pkg/controller/account/byoc.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/reuse.go, pkg/controller/accountpool/accountpool_controller.go, pkg/controller/utils/conditions.go, pkg/localmetrics/localmetrics.go, pkg/totalaccountwatcher/totalaccountwatcher.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Fixes:
https://issues.redhat.com/browse/OSD-4030
https://issues.redhat.com/browse/OSD-4033
https://issues.redhat.com/browse/OSD-4032
https://issues.redhat.com/browse/OSD-4031
In the pervious metrics implementation, the metrics are updated in each reconcile loops. This way is not very reusable because if we add a new controller, maybe we have to add metrics update logic to its reconcile loop as well.
The main idea of refactoring is to move the metrics update logic out of the reconcile loop and it is also better to put all metrics collecting stuff in one place so it can be easily reused .
A common practice in controller metrics is https://github.com/coreos/prometheus-operator/blob/master/pkg/alertmanager/collector.go. We just need to implement a …
=> Refactor metrics collector

pkg/controller/accountclaim/accountclaim_controller.go
Replaces references to UHC in accountclaim_controller.go with OCM
=> Replaces UHC references in accountclaim_controller.go

pkg/awsclient/client.go, pkg/awsclient/iam.go, pkg/awsclient/mock/mock_client.go, pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/byoc_test.go, pkg/controller/accountclaim/reuse.go
This PR alters the creation of the BYOCAdminAccess role to match osdManagedAdmin and osdManagedAdminSRE users creation to be unique per cluster/accountclaim.
=> Create and Delete BYOCAdminAccess role per cluster

pkg/controller/account/account_controller.go, pkg/controller/accountclaim/reuse.go
For readability and brevity, this commit collapses mini-methods of the
form:
```go
if condition {
return true
}
return false
```
to
```go
return condition
```
=> Refactor: collapse trivial conditionals

pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/accountclaim_controller_test.go, pkg/controller/accountclaim/accountclaim_suite_test.go, test/fixtures/clientErrors.go
Sometimes, when attempting to run the finalizer on an accountclaim the secrets watcher will update the CR in an attempt to rotate the credentials, which will cause the finalizer to fail and the account to go into a failed state.
This PR is designed to catch that specific error and requeue instead of failing the account.
=> Fix account failure race condition

hack/templates/aws_v1alpha1_ccs_accountclaim_cr.tmpl, pkg/controller/accountclaim/accountclaim_controller.go
* Creates the osdManagesAdmin secrets as `aws` in the CCS accouncClaim namespaces alongside the `byoc` secrets.
* Replaces references to UHC in accountclaim_controller.go with OCM
REF: https://issues.redhat.com/browse/OSD-3573
=> OSD 3573 ensure ccs uses osdmanagedadmin creds

pkg/controller/accountclaim/accountclaim_controller.go
Functions are not used within the codebase.
=> Removes `getAccountClaimList` and `AWSAccountIDClaimed` from accountclaim_controller.go

Makefile
This breaks the long string of targets in `test-ccs` into `create-ccs` and `delete-ccs` targets.  This will allow us to spin up a CCS cluster by calling the `create-ccs` target directly, for testing things manually when necessary.  `delete-ccs` will handle cleanup.  This also matches the behavior for `test-account`.
The `test-ccs` target still behaves as it did before, with `create-ccs` and `delete-ccs` referencing the same targets that were originally there.
=> Splits test-ccs into create-ccs and delete-ccs targets

Makefile, test/integration/api/delete_account_secrets.sh, test/integration/test_secrets.sh
Adds the ability to test that
* Expected secrets are present at the end of account creation
* Expected secrets have expected keys
To Test:
* `make test-account-creation`
* It should now verify that the secrets are present.
Or if you already have an `osd-staging-1` account created:
* `make test-secrets`
=> Adds secret testing to Account Creation tests

README.md, pkg/controller/accountclaim/accountclaim_controller.go
Fixes some minor Go Lint errors: adds comments to exported constants; fixes non-standard constant case
=> Fixes some minor Go Lint errors

pkg/controller/account/account_controller.go, pkg/controller/utils/conditions.go, pkg/localmetrics/localmetrics.go
Signed-off-by: Ben Ye <yb532204897@gmail.com>
Summary metrics are collected in client side, which means every time the operator restarts (maybe triggered by CD update), the current metrics will be lost. Histogram also has some other advantages.
So this pr updates the metrics type to histogram.
=> Change summary metrics to histogram

pkg/controller/account/credentials_rotator.go
During the refactor from BYOCAdminAccess to BYOCAdminAccess-uid I missed this bit.
=> Use BYOCAdminAccess-uid role for secret rotation

pkg/localmetrics/localmetrics.go
Signed-off-by: Ben Ye <yb532204897@gmail.com>
Adjust the buckets based on the observations on our dashboard.
=> Adjust histogram buckets and rename reconcile metric

pkg/controller/account/account_controller.go, pkg/controller/account/cases.go
...to make it easier to trace a support case back to the associated Account CR.
=> Add Account.Name to support case body

Makefile, README.md, cmd/manager/main.go, hack/scripts/edit_operator_yaml_for_dev.py, pkg/controller/account/account_controller.go, pkg/controller/utils/utils.go
Adds support for `FORCE_DEV_MODE=cluster`, which still skips AWS support
case creation, but serves metrics from the cluster as normal.
Renames the `deploy` make target to `predeploy`.
Introduces a `deploy-local` target which invokes the appropriate
`operator-sdk` command for you, with `FORCE_DEV_MODE_=local`.
Introduces a `deploy-cluster` target which deploys the operator in the
"real" cluster you're logged into, with `FORCE_DEV_MODE=cluster`.
=> Support for 'cluster' dev mode

deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Adds DirectConnect permissions based on Customer Facing Documentation.
Needs to be merged after https://github.com/openshift/aws-account-operator/pull/390
=> Adds broken down permissions for Direct Connect

pkg/awsclient/client.go, pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/credentials_rotator.go, pkg/controller/account/ec2.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/accountclaim_controller_test.go, pkg/controller/accountclaim/organizational_units.go, pkg/controller/accountclaim/reuse.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, pkg/controller/awsfederatedrole/awsfederatedrole_controller.go, pkg/totalaccountwatcher/totalaccountwatcher.go, pkg/totalaccountwatcher/totalaccountwatcher_test.go, test/integration/federated_access_cr_test.go
Building on [OSD-2839](https://issues.redhat.com/browse/OSD-2839), this commit refactors AWS Client generating such that it is done the same way by all controllers, and is easily mocked for testing purposes.
With this commit, the `awsclient` package exposes:
- A `Builder` interface with a `GetClient` method whose contract is identical to the (now gone) GetAWSClient func (except it now needs a receiver).
- A `RealBuilder` empty concrete implementation of `Builder`, whose `GetClient` method is exactly the artist formerly known as `GetAWSClient`.
- A `MockBuilder` concrete implementation of `Builder`. This struct has a field for a `gomock.Controller`, and its `GetClient` method returns a singleton instance of the mocked AWS client (from generated code in the `mock` package).
- A …
=> Consistent, mockable AWS Clients

pkg/controller/accountclaim/reuse.go
Fixes an issue where the CCS Account CR is properly deleted but the CCS AccountClaim's finalizer hasn't been removed.  Currently, the operator hot loops on this error if the AccountClaim gets in this state. This change will make sure the rest of the CCS AccountClaim finalizer logic is ran.
=> Don't error if BYOC AccountClaim finializing can't find Account CR

pkg/controller/accountclaim/reuse.go
Turns out if the Account doesn't exist, there's a nil pointer. Who knew?
This PR makes sure the BYOC secret finalizer logic is removed if the AccountClaim finalizer hotloop situation is hit.
=> Make sure byoc secret finalizer is gone then return

pkg/awsclient/client.go, pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/credentials_rotator.go, pkg/controller/account/ec2.go, pkg/controller/accountclaim/organizational_units.go, pkg/controller/accountclaim/reuse.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, pkg/controller/awsfederatedrole/awsfederatedrole_controller.go, pkg/localmetrics/localmetrics.go, pkg/localmetrics/localmetrics_test.go, pkg/totalaccountwatcher/totalaccountwatcher.go
Instrument AWS API calls to report duration and count metrics in a fashion similar to what #410 did for kubeclient calls.
At this time the `resource` label gets assigned the host, which indicates which AWS service we hit. In the future we may want to drill into the payloads to report the operation more specifically.
Jira: [OSD-4507](https://issues.redhat.com/browse/OSD-4507)
=> Metrics for API Calls (2 of 2: AWS)

pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
If the uid or awsAccountID label are missing, and the CR is not Ready, then we can safely skip the rest of the cleanup code since the role will not have been created.
=> Continue finalizer cleanup for AWSFederatedAccountAccess 

pkg/controller/account/account_controller.go, pkg/totalaccountwatcher/totalaccountwatcher.go, pkg/totalaccountwatcher/totalaccountwatcher_test.go
Refactors the account creation logic to handle the gating of this entirely in the Total Account Watcher instead of in the account controller.
=> Refactors and adds tests for account creation logic

pkg/controller/account/byoc_test.go, pkg/controller/accountclaim/organizational_units_test.go
These tests were lax in two ways:
- There was no `.Finish()`, so mock calls weren't being validated.
- The mock `EXPECT()`s were using `.AnyTimes()`, which means that (even once the `.Finish()` was added) the expected calls could be missed and the test would still pass.
(The mocks were still partially effective in that they were setting up appropriate `Return()` values.)
This commit adds the `.Finish()`es and removes the `.AnyTimes()`s. This enforces that each `EXPECT()`ed call is made exactly once (the default if you don't use any `*Times()`), and that no un`EXPECT()`ed calls are made.
=> Strictify AWS mocks for BYOC and OU tests

pkg/localmetrics/localmetrics.go
In the kube API call path, we're only reporting metrics if the request "succeeds", meaning that it returns a real Response (even if that Response is 4xx/5xx). But in the AWS call path, we may still encounter a request failure such that the Response is `nil`. This was panicking the metrics reporting where we fill in the `status` label with the response's HTTP status.
With this commit, we defend against that by checking for a `nil` response and registering `{ERROR}` in the `status` label.
=> API call metrics: Defend against `nil` Response

hack/olm-registry/olm-artifacts-template.yaml
`11:27:49 [2020-08-10 15:27:49] [ERROR] [openshift_base.py:realize_data:343] - [hive-stage-01/aws-account-operator] [https://api.hive-stage-01.n1u3.p1.openshiftapps.com:6443]: The AccountPool "hive-stage-01" is invalid: spec.poolSize: Invalid value: "string": spec.poolSize in body must be of type integer: "string"`
=> fix invalid type error

hack/olm-registry/olm-artifacts-template.yaml
`12:08:42 [2020-08-10 16:08:42] [ERROR] [openshift_base.py:realize_data:343] - [hive-stage-01/aws-account-operator] [https://api.hive-stage-01.n1u3.p1.openshiftapps.com:6443]: The AccountPool "hive-stage-01" is invalid: spec.poolSize: Invalid value: "string": spec.poolSize in body must be of type integer: "string"`
=> invalid type error fix

pkg/apis/aws/v1alpha1/accountclaim_types.go, pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/iam.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/reuse.go, pkg/controller/utils/status.go
This includes a number of changes to facilitate surfacing of underlying account failure messages to OCM for CCS accounts, as well as more details error messages for standard accounts upon failure.  It also renames some "BYOC" items to "CCS", and consolidates some code used between both standard and ccs accounts into one place.
This incorporates the bugfixes from #424, and must be merged after.
The complete changelog:
- Adds function to report failed accounts to account claim, retrieve account claim to the account controller
- Removes byoc-specific function for the above, so both types share the same code
- Renamed "SetAccountStatus" to "SetAccountCondition" to match actual workings; renamed "BYOCAccountFailedClaim" to "CCSAccountFailedClaim"
- Renames "setStatusFailed" to "setStateFailed" …
=> OSD 3978 granular status reports

Makefile, pkg/apis/aws/v1alpha1/account_types.go, pkg/controller/account/account_controller.go, pkg/controller/account/ec2.go
TL;DR: free up the Account controller to carry on servicing events for
other Accounts while regions are being initialized.
Background: Initializing supported regions can take a nontrivial amount
of time.  Previously the regions were initialized in parallel, but the
parent account controller Reconcile would wait for all of those threads
to complete.  Thus the controller's ability to service the next event
was constrained to however long the longest region init took. As
currently written, this is a theoretical maximum of 50 minutes if we hit
all the timeouts, but is always at least four seconds plus four AWS API
calls.
With this commit, we set a new state, InitializingRegions, and decouple
the parent of these threads from the main account controller Reconcile,
spawning it in its own thread …
=> Make region init fully asynchronous

cmd/manager/main.go, pkg/controller/account/account_controller.go, pkg/controller/utils/utils.go
Commit 801903c1 (PR #454) made region initialization happen in the
background. To prevent subsequent reconciles of the same Account from
thrashing, it introduced a new InitializingRegions state which was
ignored by the controller; unless a really long time elapsed, whereupon
we assumed the goroutine died and we set the account to Failed.
This caused a regression: Previously, Accounts stayed in Creating while
regions were being initialized. If the operator died, it would come back
up and churn through to the region initialization code path again. With
the new InitializingRegions state, that wasn't happening.
With this commit, we restore that behavior by detecting whether the
InitializingRegions condition was set earlier than the start time of the
operator. If so, we assume it's dead, and …
=> Detect and recover stale region initialization

pkg/controller/account/account_controller.go, pkg/controller/account/account_finalizer.go, pkg/controller/account/byoc.go
Uses individual error variables (for clarity) and catches and returns them, to create framework for more specific error handling.  This will allow for better surfacing of errors to OCM.
Moves reconcile.Result logic for CCS into initializeNewCCSAccount, to allow flexibility in how or when the account is re-queued based on the types of errors it encounters.  This sets the stage for handling specific errors, and treating them as necessary (ie, mark account failed and do not re-queue, retry, or retry after X period of time).
Part 2 of OSD-3978 "granular status reports"
Depends on #425
=> OSD-3978 Refactor error handling & logging, reconcile logic for CCS account initialization for flexible re-queuing (pt 2)

deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Instead of completely removing legacy permissions some made sense to keep, so I added them.
I took the liberty of getting rid of GuardDuty reporting.  That's not applicable to Network Management and if we want to enable customer self-service for that then we should consider adding a separate role they can assume.
I do have questions about others, though:
=> Cleans up Legacy Permissions into blocks.

pkg/controller/account/ec2.go
This renames the "instanceId" parameter for the "DescribeEC2Instances" function in the pkg/account/ec2.go file to "instanceID", to conform with linter standards.
=> Tiny Fix: Rename function parameter for linter

pkg/controller/account/account_controller.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountpool/accountpool_controller.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, pkg/controller/awsfederatedrole/awsfederatedrole_controller.go, pkg/controller/utils/reconcilermetrics.go, pkg/localmetrics/localmetrics.go
Add a new `error` label to the `aws_account_operator_reconcile_duration_seconds` metric. This gets the value `true` or `false` according to whether the wrapped `Reconcile` returned a non-nill `error`.
=> Reconciler metrics: count errors

pkg/controller/account/account_controller.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountpool/accountpool_controller.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, pkg/controller/awsfederatedrole/awsfederatedrole_controller.go, pkg/controller/utils/reconcilermetrics.go
We're about to add a success/error dimension to the Reconciler duration metric. Doing so inline would entail creating a wrapper func for each controller's Reconcile. Each such wrapper func would have the same code in it.
Instead, prepare by factoring the existing reporting into a utility. This will allow the subsequent commit to add the new dimension in one place rather than having to touch all the controllers.
The utility exposes a wrapper factory, `NewReconcilerWithMetrics`, that accepts and returns a Reconciler. Its job is to
- Log the start & completion messages.
- Time the wrapped Reconciler's Reconcile func and report it to the appropriate prometheus Collector.
Now controllers no longer need to do the above. Instead they simply wrap their locally-defined Reconciler instance via the …
=> Factor out Reconciler metrics

pkg/controller/account/account_controller.go
We refuse to create accounts when the count according to AWS exceeds the configmap's account-limit. Previously this condition triggered an immediate requeue, which would hot-loop the account controller, because
- The count according to AWS effectively never decreases.
- The configmap doesn't get updated frequently.
With this commit, we inject a 15-minute delay before requeueing to avoid this hot loop.
=> Delay requeue when account limit reached

pkg/controller/account/ec2.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
There were a few files where pkg/controller/utils was being imported twice with different aliases. Consolidate.
Note that in these cases I chose to retain the `controllerutils` alias, since `utils` is so generic. However, I didn't go back through and change all the other files where that alias isn't used.
=> Consolidate duplicate pkg/controller/utils imports

cmd/manager/main.go, pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/awsfederatedrole_types.go, pkg/controller/account/byoc.go, pkg/controller/account/byoc_test.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, pkg/controller/utils/utils.go
Fulfills OSD-4893.  Prerequisite to https://github.com/openshift/osd-utils-cli/pull/68
This PR is a pre-requisite to being able to assume the BYOCAdminAccess role in CCS accounts.  This PR adds a second principal to the BYOCAdminAccess role.
For SREs to access that role they first assume the RH-SRE-CCS-Access role in the payer account that the account was created in and then using the STS credentials for that role they should be able to further access the BYOCAdminAccess role in the customer's account.
To test:
* `make create-ccs`
* `oc get accountclaim --all-namespaces` and note the hash at the end of the account CR name
* `unset AWS_SESSION_TOKEN AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY` to ensure that your env vars are clear
* `aws sts assume-role --role-arn arn:aws:iam::[staging2 …
=> Add role for ccs access

standard.mk
[osd-operators-registry](https://github.com/openshift/osd-operators-registry) is obsolete; and aws-account-operator was never integrated into it anyway. Remove `make` targets that existed solely for its use.
=> Remove osd-operators-registry targets

.golangci.yml, Makefile, cmd/manager/main.go, config/config.go, pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/awsfederatedrole_types.go, pkg/awsclient/iam.go, pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/byoc_test.go, pkg/controller/account/ec2.go, pkg/controller/account/iam.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/accountclaim_controller_test.go, pkg/controller/accountclaim/reuse.go, pkg/controller/accountpool/accountpool_controller.go, pkg/controller/accountpool/accountpool_controller_test.go, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, pkg/controller/awsfederatedrole/awsfederatedrole_controller.go, pkg/controller/awsfederatedrole/finalizer.go, pkg/controller/utils/conditions.go, pkg/controller/utils/utils.go, pkg/localmetrics/localmetrics.go, pkg/totalaccountwatcher/totalaccountwatcher.go, pkg/totalaccountwatcher/totalaccountwatcher_test.go
This PR includes a number of fixes to conform to Go linter standards from golangci-linter.  Mostly this includes adding or fixing comments for exported functions, constants and variables.  In a few cases, like the `totalaccountwatcher`, exported-but-unused-outside-the-package functions were changed to be unexported.
Also adds default SREP boilerplate .golangci.yml file provided by @2uasimojo.
Commits have not been squashed so they may be addressed as is, if desired.
Note: `pkg/controller/testutils/testutils.go` has a few linter notices that I am unsure how to fix.  Otherwise, with #471, this handles all the linter issues I could find.
=> Adds various fixes for Go linter standards

Makefile, hack/templates/aws_v1alpha1_configmap.tmpl
card -> https://issues.redhat.com/browse/OSD-5095
Add step to the predeploy Makefile target, making sure the a-a-o configuration configMap (aws-account-operator-configmap) gets created.
=> Deploy configmap in make

Gopkg.lock, pkg/controller/account/account_controller.go, pkg/controller/account/iam.go, vendor/github.com/avast/retry-go/LICENSE, vendor/github.com/avast/retry-go/options.go, vendor/github.com/avast/retry-go/retry.go
This adds a conditional, retry with exponential backoff to the CreateAccessKey request, to handle specific errors that may be recoverable with a retry, to address InvalidClientTokenID errors that appear under load in some cases.
It also removes a duplicate setting of account state:
The `RotateIAMAccessKeys` function called `utils.SetAccountStatus` to set the account to failed if creating a new IAM user access key failed, but if that function returns an error to `BuildIAMUser`, `BuildIAMUser` will return an error to the reconcile loop, which also attempts to set the state to failed.
This removes the duplicate from `RotateIAMAccess Keys`, and reformats the error log message that is generated to make use of the searchable/indexable fields.
Signed-off-by: Christopher Collins …
=> Adds conditional retry for some specific errors, eg: InvalidClientTokenID

Makefile, pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
...and add the flags to `golangci-lint` that prevents it from stopping after a certain number of errors.
=> Fix more linting errors

pkg/controller/account/account_controller.go
We forgot a multiplication by `time.Minute`, so we were ending up with 60s + 50ns instead of 60s + 50min. Fix.
=> Fix region init timeout

pkg/controller/account/iam.go
Retries on AccessDenied within IAM errors due to eventual consistency issues.
Satisfies [OSD-5677](https://issues.redhat.com/browse/OSD-5677)
=> Add AccessDenied retry.

go.mod, go.sum, pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/accountclaim_types.go, pkg/apis/aws/v1alpha1/shared_types.go, pkg/awsclient/iam.go, pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/utils/status.go
Each existing code path that leads to a failed account has a new, representative condition with a descriptive TYPE, REASON and MESSAGE.
Card -> https://issues.redhat.com/browse/OSD-5396
=> Created more account and accountclaim conditions

test/integration/issue27333.go
Adds a workaround for https://github.com/golang/go/issues/27333 to make `make coverage` work.
=> Fix `make coverage`

Makefile, hack/scripts/set_operator_credentials.sh
This PR updates the Makefile to fix the predeploy step so that it works
with your downloaded AWS Profiles, and also adds a clean step to the
make test-all step so that the tests won't be impacted by any dangling
resources.
Satisfies [OSD-5401](https://issues.redhat.com/browse/OSD-5401)
=> Updates predeploy step and cleans operator

pkg/awsclient/client.go, pkg/controller/utils/clientwrapper.go, pkg/localmetrics/localmetrics.go, pkg/localmetrics/localmetrics_test.go
AWS's `awserr.Code()` seems to be an ENUM of strings that are fixed and not changeable (i.e. they won't be "ErrNoAccount12345" but it will be "ErrNoAccount" or something, so we should be able to filter down on these error codes.  This should include any Rate Limit errors (although they seem to be different for each service :( ))
Satisfies OSD-5391
=> Adds AWS Error Code to Metrics

deploy/crds/aws.managed.openshift.io_v1alpha1_awsfederatedrole_readonly_cr.yaml, hack/olm-registry/olm-artifacts-template.yaml
related to https://issues.redhat.com/browse/OSD-6671
OCM users use the AWS Infrastructure Access feature to gain access to the cluster's AWS account. They can either choose read-only or network-mgmt roles.
To enable OSD users to properly use the new Log Forwarding feature, it is expected that users can go to the cluster's AWS account and get the logs from there. When trying to do that currently, a user gets a permission error (`not
authorized to perform: logs:DescribeLogGroups`).
This PR adds the `CloudWatchReadOnlyAccess` managed policy to the Read only access policy.
=> Add CloudWatchReadOnlyAccess managed policy to Read only users

deploy/crds/aws.managed.openshift.io_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml, hack/olm-registry/olm-artifacts-template.yaml
In order for hive accounts to create VPC attachmetns to Transit Gateways in external accounts, the above AWS managed role is required.
Reference:
https://docs.aws.amazon.com/vpc/latest/tgw/tgw-service-linked-roles.html
=> Add  AWSServiceRoleForVPCTransitGateway AWS Managed Role To Network Mgmt Role

deploy/crds/aws.managed.openshift.io_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml, hack/olm-registry/olm-artifacts-template.yaml
Follow-up PR to https://github.com/openshift/aws-account-operator/pull/528 to add rules directly.
Reference: https://docs.aws.amazon.com/vpc/latest/tgw/tgw-service-linked-roles.html
=> Add AWSServiceRoleForVPCTransitGateway Rules Directly

deploy/crds/aws.managed.openshift.io_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml, hack/olm-registry/olm-artifacts-template.yaml
This adds additional permissions in order for service-linked roles to be created (necessary for creating vpc attachments to transit gateways).
Also removed invalid actions found during testing.
Ref: https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html
=> Add TransitGateway Service-Linked Role Permissions

.gitignore
`.envrc` is used with `direnv`.
PTAL
=> Ignore .envrc

hack/scripts/set_operator_configmap.sh, hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Add script to generate configmap for running the aws-account-operator.
Fix template to use a parameter reference for the namespace as oc template will strip out the value if its fixed.
=> Add script to generate configmap

deploy/crds/aws.managed.openshift.io_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml, hack/olm-registry/olm-artifacts-template.yaml
This will allow tags to be created/deleted for transit-gateway-attachments.
Related card: https://issues.redhat.com/browse/OSD-6748
=> Allow ec2:CreateTags on transit-gateway-attachments

deploy/crds/aws.managed.openshift.io_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml, hack/olm-registry/olm-artifacts-template.yaml
Actions needed for PrivateLink and VPC to private zone associations.
https://issues.redhat.com/browse/OSD-6928
Ref: 
https://docs.aws.amazon.com/Route53/latest/APIReference/API_AssociateVPCWithHostedZone.html
https://github.com/openshift/hive/blob/master/docs/awsprivatelink.md#using-aws-private-link
=> Add Route53 VPC Zone Association Rules

Makefile
* Cleaned up Makefile from duplicate code 
* Introduced the `deploy-local-debug` target to run the operator locally with delve server enabled
* Fixed `create-accountclaim` target because it overlapped with `create-account`.
PTAL
=> Decouple Makefile

Makefile, hack/scripts/set_operator_configmap.sh, hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
A few updates:
* Added the `check-ou-mapping-configmap-env` target to execute before we create the ConfigMap, because missing the BASE and ROOT OU IDs will cause the Operator to return errors. 
*  Since we merged #514, I use the script to generate the ConfigMap. I am not sure about the VCPU Quota default to 1, but I believe it should be fine. 
* Fix `delete-ou-map` to explicitly set the OPERATOR_NAMESPACE
PTAL
=> Improve ConfigMap creation & deletion process

Makefile, README.md, deploy/crds/aws.managed.openshift.io_accountclaims_crd.yaml, deploy/crds/aws.managed.openshift.io_accounts_crd.yaml, docs/1.0-Installation.md, hack/olm-registry/olm-artifacts-template.yaml, hack/scripts/test_envs, hack/templates/aws.managed.openshift.io_v1alpha1_sts_accountclaim_cr.tmpl, pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/accountclaim_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go, pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/iam.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/reuse.go
After some quick experimentation this PR adds "STSMode" to the operator. Fulfills [OSD-6555](https://issues.redhat.com/browse/OSD-6555)
This still depends on some upstream dependencies.
To test:
* Follow the instructions in the updated Install docs to create the jump role and access role.
* Create the Jump Role and Policy
* Create the Access Role and attach Admin policy
* Update the aws-account-operator configmap
* Add the required environment variable `STS_ROLE_ARN`
* I've found it's just easier to manually verify through the CLI you can use your payer-account user creds to assume role into the jump role, and then assume the access role.
* start the operator and run `make test-sts-accountclaim`
TODO/TO CARD:
=> Updates operator to have STS Mode

pkg/controller/account/iam.go
I misunderstood what @dkeohane meant with one of the comments on a previous review and the other PR was already in the process of merging when I realized my error.
Thanks Dan!
=> Removes missed STS comment

hack/scripts/set_operator_credentials.sh
Running `make predeploy`  with a `Kind` cluster in the background returns the following error:
```
hack/scripts/set_operator_credentials.sh osd-staging-1
Deploying AWS Account Operator Credentials using AWS Profile osd-staging-1
error: failed to read input object (not a Template?): unable to recognize "hack/templates/aws.managed.openshift.io_v1alpha1_aws_account_operator_credentials.tmpl": no matches for kind "Template" in version "template.openshift.io/v1"
error: no objects passed to apply
make: *** [deploy-aws-account-operator-credentials] Error 1
```
`Template` is an OpenShift concept and that's why it's not being found in `Kind`. A workaround that @rogbas suggested was to use `oc` to process a template in `local-mode`, and pipe the output to `oc apply`.
Based on @rogbas' …
=> make predeploy work with kind cluster

deploy/crds/aws.managed.openshift.io_accountclaims_crd.yaml, hack/olm-registry/olm-artifacts-template.yaml, pkg/apis/aws/v1alpha1/accountclaim_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Adds necessary field to AccountClaim CR to enable Support ARN entry for
STS clusters
Necessary for additional work on [OSD-6757](https://issues.redhat.com/browse/OSD-6757)
=> Adds necessary field for Support ARN

pkg/controller/account/byoc.go, pkg/controller/utils/status.go
This should avoid our nil pointer dereference we found this morning.  We're attempting to update the status when we cannot get the accountclaim object, so therefore it's probably always nil here.
Fixes [OSD-7226](https://issues.redhat.com/browse/OSD-7226)
=> Avoids nil pointer dereference

Makefile
Move the evaluation of `AWS_IAM_ARN` into the `check-aws-account-id-env` target to avoid it being evaluated a) for targets where it's unused; and b) for autocomplete (where it's also unused).
Tested the following permutations:
- Unset in the environment
- Autocomplete doesn't attempt to set it
- `check-aws-account-id-env` attempts to set it. On failure, an error is output and the value is empty; so the `check-aws-account-id-env` target fails as desired.
- Set in the environment
- Autocomplete doesn't attempt to set it
- `check aws-account-id-env` succeeds with "nothing to do" (because the `ifndef` directives end us up with an empty target).
[OSD-6975](https://issues.redhat.com/browse/OSD-6975)
=> OSD-6975: Only evaluate AWS_IAM_ARN when needed

hack/olm-registry/olm-artifacts-template.yaml, pkg/apis/aws/v1alpha1/shared_types.go, pkg/awsclient/iam.go, pkg/awsclient/tags.go, pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/ec2.go, pkg/controller/account/iam.go
Adds a configmap lookup to add a custom list of tags to AAO created resources.
Satisfies [OSD-6926](https://issues.redhat.com/browse/OSD-6926)
To Test:
• Add a new Configmap entry under data named `AWS-Managed-Tags` in the following format:
```
data:
AWS-Managed-Tags: |
red-hat-managed=true
another-tag=anotherthing
some-base64=soembasec6t324aslkreoweaskleDIasdjMIT==
```
And create an account.  IAM User `OSDManagedAdmin` and EC2 instances created for account init should have the 3 additional tags defined in the configmap.  If `OSDManagedAdmin` is already created inside of your AWS account, it will _not_ get the additional tags, and you will need to delete the IAM user and create the account.
`OSDManagedAdminSRE` has been found to get no tags, and a bug card has been created for that.
=> Adds Managed Tags to AAO Created Resources

deploy/crds/aws.managed.openshift.io_accountclaims_crd.yaml, hack/olm-registry/olm-artifacts-template.yaml, hack/templates/aws.managed.openshift.io_v1alpha1_sts_accountclaim_cr.tmpl, pkg/apis/aws/v1alpha1/accountclaim_types.go, pkg/apis/aws/v1alpha1/shared_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go, pkg/awsclient/iam.go, pkg/awsclient/tags.go, pkg/controller/account/account_controller.go, pkg/controller/account/byoc.go, pkg/controller/account/ec2.go, pkg/controller/account/iam.go
For Conditional IAM policies to work, RunInstances must also be passed a
tag list for volume resource types, otherwise the RunInstances call will
not be able to create the backing volume it needs to run the instance.
Satisfies [OSD-6625](https://issues.redhat.com/browse/OSD-6625)
Depends on #572 to be merged first.  View only the commits from this PR here: [`0b4f8d8` (#562)](https://github.com/openshift/aws-account-operator/pull/562/commits/0b4f8d8a5711e8e449515554a6b6c594f9e0256e)
=> Adds tags to volumes on RunInstances calls

OWNERS
This removes me from the reviewers group in the `OWNERS` file, since I'm
not involved with the project directly anymore.
=> Removes clcollins from reviewers

pkg/controller/account/ec2.go
Card: https://issues.redhat.com/browse/OSD-6848
Instead of outputting vCPU quota error  simply log that the vCPU value was not found in the configmap and that the value is being defaulted to 0
=> Instead of outputting cVPU quota error just log the defaulting value

pkg/controller/account/account_controller.go, pkg/controller/account/ec2.go
The AWS account operator will call `DescribeRegions` to gather a list of regions to initialize when setting up a AWS account.
If a user chooses one of the 4 opt-in regions but hasn't enabled it in AWS the region will not be returned by the DescribeRegions AWS API call and we want to fail.
Card: https://issues.redhat.com/browse/OSD-7417
=> Ensure region in the AccountClaim is returned from DescribeRegions API call

pkg/apis/aws/v1alpha1/accountclaim_types.go
STS AccountClaims are entering the error state because during validate we're checking to see if credentials exist on the AccountClaim which by design wont exist for STS.
=> Ensure we validate STS AccountClaims first

pkg/controller/accountpool/accountpool_controller.go
Instead of checking for a wide range of states in Account Pool controller, I use an already existing func that checks against pre-defined account states and tells us whether an Account operation has failed or not, depending on the state. That way we avoid the case of blocking the controller because a random state doesn't conform with Account operations.
PTAL @iamkirkbater @rogbas @lisa 
See https://issues.redhat.com/browse/OSD-7460
=> [OSD-7460] check against pre-defined account states 

pkg/controller/account/account_controller.go, pkg/controller/account/account_controller_test.go, pkg/controller/accountclaim/reuse.go, pkg/controller/utils/utils.go
This change updates non-CCS accounts to use the same naming convention as the CCS accounts for the OSDManagedAdmin and OSDManagedAdminSRE usernames, appending the IAMUserIDLabel from the account.
REF: [OSD-5393 - Update non-CCS account management process to unify naming standards with CCS](https://issues.redhat.com/browse/OSD-5393)
=> Unifies CCS and Non-CCS account naming conventions

Makefile, docs/0.1-Glossary.md, docs/1.0-Installation.md, docs/1.1-InstallationPrerequisites.md, docs/2.0-Custom-Resources-and-Controllers.md, mkdocs.yml
Populate `https://openshift.github.io/aws-account-operator/` with
HTML static files generated automatically from within `docs/` dir.
- New Makefile options `serve` serves the site locally.
- GH Action for publishing the docs on push (master branch)
- Configure `mkdocs` to use `docs` as the source of markdown files.
Note: Configure GH-Pages for AAO to assume that docs reside in `docs`
dir in the repo root.
REF: [OSD-6207](https://issues.redhat.com/browse/OSD-6207)
=> Generate docs

Makefile, pkg/apis/aws/v1alpha1/accountclaim_test.go, pkg/apis/aws/v1alpha1/accountclaim_types.go
Adds back AWS Secret Ref Validation, this time with More Testing.
Satisfies: [OSD-7469](https://issues.redhat.com/browse/OSD-7469)
=> Adds back AWS secret ref validation

hack/olm-registry/olm-artifacts-template.yaml, pkg/awsclient/client.go, pkg/awsclient/mock/zz_generated.mock_client.go, pkg/controller/account/account_controller.go, pkg/controller/account/account_controller_test.go
This adds tags to non-ccs accounts on creation. This contains their respective shard names. [OSD-7360](https://issues.redhat.com/browse/OSD-7360)
=> Add tags to non-ccs accounts on creation

test/deploy/aws.managed.openshift.io_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Alternative to #614 
reference https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-associate-vpcs-different-accounts.html
[OSD-7873](https://issues.redhat.com/browse/OSD-7873)
=> Allow for management of Route53 VPC Association Authorizations

pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
In the AWS Federated Account Access controller, there was a code for deleting policies after all operations are done, but due to a wrong check between the policy name and the actual attached policy name, the condition was never met and the deletion path was not executed and that lead to leaking policies. The issue was that the attached policy in AWS has a uid label as a suffix appended to the actual policy name. 
Example format:
- BillingReadOnlyAccess-48zkrs
- CustomerAdministratorAccess-6pvv82
But the policy name in the if the condition was just `BillingReadOnlyAccess`. This PR fixes the policy leaking.
PTAL 
See: https://issues.redhat.com/browse/OSD-7720
=> [OSD-7720] Fix AWS Federated Account Access from leaking Policies

pkg/controller/account/byoc.go
No card, this is the reason that \#589 was failing silenty.
=> Fixes silent failure condition on failed BYOC claim

pkg/controller/account/iam.go, pkg/controller/account/iam_test.go, pkg/controller/accountclaim/reuse.go
[OSD-6506](https://issues.redhat.com/browse/OSD-6506)
- Reworked IAM Clean in reuse.go into iam.go
- Wrote IAM unit tests
Cleaned this up as a first step for [OSD-6505](https://issues.redhat.com/browse/OSD-6506).
The follow on PR for this body of work can be found [here](https://github.com/openshift/aws-account-operator/pull/596), adding a `finalizeAccount` func which will rely on the updated call to `CleanUpIAM` 
PTAL
=> [OSD-6506] IAM Refactor and Unit Testing

pkg/controller/account/account_controller.go, pkg/controller/account/account_controller_test.go, pkg/controller/utils/utils.go
Ref: [OSD-5393](https://issues.redhat.com/browse/OSD-5393)
- PR to reintroduce work originally developed [here](https://github.com/openshift/aws-account-operator/pull/491).
- The original PR for this was reverted [due to the removal of this section in reuse.go](https://github.com/openshift/aws-account-operator/pull/491/files#diff-2c1de2a24d3be327cfb86c6b468dc265bb87f1d3f16cdc020d0c42c41e8bc872L90) which has not been included in this PR.
- This change caused all IAM users to be cleared from CCS and non-CCS accounts, leading to [OSD-7613](https://issues.redhat.com/browse/OSD-7613)
PTAL
=> [OSD-5393] Unifies CCS and Non-CCS account naming conventions

pkg/apis/aws/v1alpha1/account_types.go, pkg/controller/account/account_controller.go, pkg/controller/account/account_controller_test.go, pkg/controller/utils/conditions.go
Card -> https://issues.redhat.com/browse/OSD-7693
Replaced `IsOlderThan` method  for `CreationConditionOlderThan`, updated tests.
=> AWS Account Operator should check for the condition status of creating rather than the creation timestamp

pkg/controller/account/account_controller.go, pkg/controller/account/account_controller_test.go, pkg/controller/account/byoc.go, pkg/controller/account/byoc_test.go
[OSD-7072](https://issues.redhat.com/browse/OSD-7072)
- Now calling `createBYOCAdminAccessRole` for all non-STS accounts within the `account_controller.go`
- Removed existing call to `createBYOCAdminAccessRole` from `byoc.go` in lieu of the change above.
- **To Note:** the big if block added to `account_controller.go` could be refactored down even further if we did not have the dependency on the RoleID within the `assumeRole` func - there's an [outstanding question over its use](https://coreos.slack.com/archives/CNJPJSG3Z/p1623934075068100), therefore this refactor may still occur
=> [OSD-7072] Adding new role to non-STS accounts

pkg/controller/account/account_controller.go, pkg/controller/account/ec2.go
This piece of code causes a client without permission to attempt region initialization multiple times even though it is not possible. This PR will simply raise the error up to a higher level where the account can be put into an error state.
This should be merged after https://github.com/openshift/aws-account-operator/pull/599 which is the PR that will actually fail accounts on failure to initialize a given region.
Card: https://issues.redhat.com/browse/OSD-7431
=> Don't wait for accounts to succeed if they are missing permissions to complete operation in the first place

pkg/controller/account/account_controller.go
This check on the setup client for Access Denied allows us to clean out
accounts that are denied access by the account owner or are otherwise
inaccessable to our operator
Fullfils [OSD-8400](https://issues.redhat.com/browse/OSD-8400)
=> Adds a check for AccessDenied on setup client init

pkg/controller/account/account_controller.go
Card: https://issues.redhat.com/browse/OSD-7820
=> We don't need to output the error because it is expected behavior

test/integration/api/create_account.sh
Encountered an issue today when calling `make create-accountclaim` when an account CR with a name of `osd-creds-mgmt-osd-staging-1` already exists, the call nukes the existing account and replaces it with a templated account CR. 
Fixed by adding a check to see if account already exists before applying new account CR.
=> Update create account script to stop nuking existing account

pkg/controller/account/byoc.go
Fixes an issue where BYOCAdminAccess prefix is being added a second time
to the role name when attempting to delete the existing role.
=> Fixes issue with BYOCAdminAccess prefix

deploy/crds/aws.managed.openshift.io_accountpools.yaml, pkg/apis/aws/v1alpha1/account_types.go, pkg/apis/aws/v1alpha1/accountpool_types.go, pkg/apis/aws/v1alpha1/zz_generated.openapi.go, pkg/controller/account/account_controller.go, pkg/controller/accountpool/accountpool_controller.go, pkg/controller/accountpool/accountpool_controller_test.go, pkg/localmetrics/localmetrics.go, pkg/totalaccountwatcher/totalaccountwatcher.go, pkg/totalaccountwatcher/totalaccountwatcher_test.go
Adds additional status fields and calculations for the same in order to start reporting better metrics on accountPool availability.
Satisfies [OSD-7754](https://issues.redhat.com/browse/OSD-7754)
=> Adds some new metrics to the accountpool status

hack/olm-registry/olm-artifacts-template.yaml, test/deploy/aws.managed.openshift.io_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
The permissions required to download a VPN config from AWS appear to have changed, which is preventing customers from downloading it themselves using network-mgmt. This adds the missing permissions.
This is generating toil, as documented in OHSS-6964, [OHSS-7075](https://issues.redhat.com/browse/OHSS-7075) and [OHSS-7264](https://issues.redhat.com/browse/OHSS-7264) where we had to manually provide the configs for the customers.
This should resolve OSD-8599.
=> allow network-mgmt to dowload the VPN configs

Makefile
This PR turns the log messages of the aao from json based:
```
{"level":"info","ts":1636103590.8215709,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8081"}
{"level":"info","ts":1636103590.8217633,"logger":"cmd","msg":"Registering Components."}
{"level":"error","ts":1636103590.822052,"logger":"controller_account","msg":"failed retrieving configmap","error":"the cache is not started, can not read objects","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/maschulz/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/openshift/aws-account-operator/pkg/controller/account.newReconciler\n\t/home/path/to/operators/aws-account-operator/pkg/controller/account/account_controller.go:94\ngithub.com/openshift/aws-account-o …
```
=> Make local log output human friendly

pkg/controller/account/account_controller.go
This PR addresses some minor logging nits observed where the parameters to the logging call were not being supplied in properly-balanced key/value pairs.
This fixes the following error being observed in the operator logs:
```
{"level":"dpanic","ts":1634650365.8639536,"logger":"controller_account","msg":"odd number of arguments passed as key-value pairs for logging", ...
```
=> Correcting some minor logging nits

pkg/controller/account/byoc.go, pkg/controller/account/byoc_test.go, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/accountclaim_controller_test.go
This PR makes sure, that the accountclaim validation happens before any account is even created by moving the validation code to `pkg/controller/accountclaim/accountclaim_controller.go`.
Additional unit tests are also added to cover the basics of creating a byoc accountclaim.
=> OSD-7210: Move AccountClaim Validation into the AccountClaim controller

docs/1.1-InstallationPrerequisites.md
This PR just adds a small section to the prerequisites docs explaining the additional iam policies need to run the operator in local dev mode.
=> Document additional iam permissions for dev setup

cmd/manager/main.go
This renames a var in the cmd.manager file that I found that was improperly named/documented.
=> Renames var that was improperly named

pkg/apis/aws/v1alpha1/account_types.go, pkg/controller/account/account_controller.go
Fix for a bug introduced:
- Found when local testing `make test-all`
- We recently added finalizers to non-CCS account CRs, but never removed the finalizer on account deletion call. Therefore, the test suite is hanging on account deletion call, as the account CR is never deleted because the finalizer is never removed.
=> Remove account finalizer for non-STS accounts to fix local testing

hack/files/aws.managed.openshift.io_v1alpha1_zero_size_accountpool.yaml
When running  "make deploy-cluster" the accountpool CR in hack/files/aws.managed.openshift.io_v1alpha1_zero_size_accountpool.yaml is getting deployed to the default namespace. This PR fixes that by adding in the namespace field in the metadata
=> Add namespace to test accountpool CR

pkg/awsclient/tags.go
Closes [OSD-7011](https://issues.redhat.com/browse/OSD-7011) - provide a name for the AWS ec2 region test instances.
=> naming the ec2 test instance that is created in each aws region

docs/3.3-AccountClaim.md, pkg/controller/account/account_controller.go
updating docs to capture some past and recent decisions around `customTags` which are passed to AAO via the `AccountClaim` that we add to AWS resources that we create.
Related to:
* [OSD-9949](https://issues.redhat.com/browse/OSD-9949)
* [OSD-10191](https://issues.redhat.com/browse/OSD-10191)
=> updating documentation around AccountClaim customTags

test/deploy/aws.managed.openshift.io_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Encountered a bug in our formatting for `test/deploy/aws.managed.openshift.io_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml` introduced in https://github.com/openshift/aws-account-operator/pull/673
=> Fix yaml formatting in awsfederatedrole_networkmgmt CR

pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/accountclaim_controller_test.go, pkg/controller/accountclaim/reuse.go
While investigating dangling accounts I looked through our accountclaim finalize functionality to try identify areas where we may not be returning errors
Previous behaviours which have been addressed as part of this PR: 
- If the accountclaim `finalizeAccountClaim` function encountered an error, we would still proceed to remove the finalizer.
- If the `cleanUpAwsAccount` func encountered an error, we simply logged it instead of returning it.
Additions:
- Added some more unit tests. 
- Made errors from AWS visible in our logging, as debugging why we can't clean up an AWS resource without the context from AWS was impossible.
Ticket ref: [OSD-9246](https://issues.redhat.com/browse/OSD-9246)
=> [OSD-9246] Block gaps in our AccountClaim finalizer handling

hack/olm-registry/olm-artifacts-template.yaml, hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl, pkg/apis/aws/v1alpha1/shared_types.go, pkg/awsclient/client.go, pkg/awsclient/mock/zz_generated.mock_client.go, pkg/controller/account/ec2.go
On non-govcloud account the operator expects there to be a default subnet to be used when creating and terminating ec2 instances. Per https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-ec2.html#govcloud-ec2-vpc govcloud accounts may or may not have a default subnet. Therefore, when in govcloud env, AAO needs to create a vpc, one subnet, run the ec2 instance, tear it all down.
=> Handle Region Initialization for FedRAMP

pkg/apis/aws/v1alpha1/shared_types.go, pkg/awsclient/awsclient_suite_test.go, pkg/awsclient/tags.go, pkg/awsclient/tags_test.go
Closes [OSD-9953](https://issues.redhat.com/browse/OSD-9953)
Adds missing unit tests for AWS resource tag builder
=> adding unit tests for tag builder

pkg/controller/account/account_controller.go
The error message wasn't necessarily a message we cared about in too much detail - and having the stack trace in the logs can be quite verbose. Dropping the log level to info and expanded upon the error message itself.
Ref ticket: https://issues.redhat.com/browse/OSD-9246
=> Update AWS Account limit reached to info level and expand on message

docs/1.0-Installation.md, docs/1.1-InstallationPrerequisites.md
The link to the manual STS setup was pointing to non-existent file.
=> Fix broken link to the manual STS setup.

pkg/controller/account/ec2.go
Added a `BlockDeviceMapping` specification to `createEC2Instance()` such that all instances created by this operator use encrypted EBS volumes by default. Volumes are encrypted with the AWS Managed KMS key and are automatically deleted upon instance termination.
This addresses OSD-10219, where the verifier fails on clusters that mandate encrypted storage universally.
=> Encrypt AWS instance EBS volume by default

pkg/controller/account/account_controller.go
This PR disables the secret probe as it significantly increases the reconcile time in production. We should investigate doing this kind of operation outside of the reconcile loop.
For the moment this PR effectively disables changes in PR #678
=> Disable secret probe

hack/olm-registry/olm-artifacts-template.yaml
In order to create HyperShift clusters whose control planes run inside
OSD clusters it is necessary to configure PrivateLink between the VPC of
the customer where the worker nodes run and the VPC of the HyperShift
management cluster. Currently this is done by the HyperShift operator
using credentials passed by app-interface, which in turn obtains those
credentials using the OCM infrastructure access roles feature to obtain
the `network-mgmt` role. That role needs to have the permission to use
the `ModifyVpcEndpointServicePermissions` API in order to configure the
cross-account permissions that are needed.
Related: https://issues.redhat.com/browse/SDE-1586  
Related: https://issues.redhat.com/browse/SDA-5527  
Related: https://issues.redhat.com/browse/HOSTEDCP-408
=> Add `ModifyVpcEndpointServicePermissions` to `network-mgmt` role

hack/scripts/aws/setup-aws-policies/AccessRolePolicy.json, hack/scripts/aws/setup_aws_accounts.sh
The script did miss the step to create the correct policy for the `AccessRole` that is created.
Without the policy the Role can not `describeRegions` in `ec2` and will fail in the `STS` scenario.
=> Update setup aws script

docs/1.1-InstallationPrerequisites.md
This is needed to have the AAO running and it can differ, depending
where osdctl assigns the account.
=> How to find correct OSD_STAGING_1_OU_BASE_ID

pkg/apis/aws/v1alpha1/account_types.go, pkg/controller/account/account_controller.go, pkg/controller/account/account_controller_test.go, pkg/controller/account/byoc.go
The condition is added when the Status.Claimed is set to true.
This happens for regular and byoc accounts.
Fixes OSD-9894.
=> [OSD-9894] Add condition when account is claimed.

hack/olm-registry/olm-artifacts-template.yaml, hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl, pkg/awsclient/client.go, pkg/awsclient/mock/zz_generated.mock_client.go, pkg/controller/add_account_validation.go, pkg/controller/utils/clientwrapper.go, pkg/controller/utils/utils.go, pkg/controller/validation/account_validation_controller.go, pkg/controller/validation/account_validation_controller_test.go
Adds a new controller to validate accounts to the operator.
Currently the validation logic only includes verifying that an unclaimed, non-ccs account is under the expected root organisation.
If this is not the case the account will be moved.
=> [OSD-9910] Add account validation controller to AAO

Makefile
Since new prow ci int test entrypoint named `prow-ci-entrypoint` is introduced in makefile ,
removing old entrypoint named `prow-ci-deploy`.
=> [RUN-INT-TEST][OSD-12227] remove unused prow-ci-deploy makefile target

go.mod, pkg/controller/accountclaim/accountclaim_controller.go, pkg/controller/accountclaim/reuse.go
This PR is effectively a no-op, but https://github.com/pkg/errors has been deprecated as all of its functionality is a part of Go stdlib now.
=> Remove deprecated github.com/pkg/errors package

hack/olm-registry/olm-artifacts-template.yaml, pkg/controller/validation/account_validation_controller.go
Adds an additional log statement to validate desired functionality
before enabling, as well as explicitly defines the feature flags as
configurable in the configmap in order to be able to run this
shard-by-shard when we're ready to turn on the flags.
Adds on to [OSD-10116](https://issues.redhat.com//browse/OSD-10116)
=> Adds additional log and updates olm template

pkg/controller/validation/account_validation_controller.go, pkg/controller/validation/account_validation_controller_test.go
All checks we currently run require the AwsAccountID to be set, so we check it early.
Prevents the logs filling up with errors, because of an invalid account id.
=> [OSD-9910] Check that AwsAccountID is set as validation.

pkg/controller/validation/account_validation_controller.go, pkg/controller/validation/account_validation_controller_test.go
Adds a check to switch which OU the account should be in based on the claimed state of the account.
Work towards completing [OSD-9910](https://issues.redhat.com//browse/OSD-9910)
=> Adds check if account is claimed before moving OU

pkg/controller/validation/account_validation_controller.go, pkg/controller/validation/account_validation_controller_test.go
Reverts openshift/aws-account-operator#724
This is hammering the AWS API at a scale we couldn't test at outside of integration, so we need to reconsider how we attempt to check if an OU exists.
=> Revert "Adds check if account is claimed before moving OU"

pkg/controller/validation/account_validation_controller.go, pkg/controller/validation/account_validation_controller_test.go
Reverts openshift/aws-account-operator#726, which removed the functionality that another PR added.
This re-adds the original functionality of trying to allow correct movement of the OU, however instead of using the accountclaim controller's naive implementation we're utilizing an in-memory map of the OUs that we've seen before to sidestep AWS Rate limits.
=> Adds check if account is claimed before moving OU - Take Two

controllers/validation/account_validation_controller.go, controllers/validation/account_validation_controller_test.go
As we already do not validate accounts that don't exist, this will also skip validation for accounts that are in the process of being deleted.
=> [OSD-13258] Do not validate accounts being deleted.

controllers/validation/account_validation_controller.go
Changes the validation controller to not care if the account has been reused before, but only care if the legal entity id is currently set. This allows us to take into consideration accounts that have had the legal entity reset and have not been claimed again, because the `reused` status is still set to true on those accounts.
Resolves [OSD-13089](https://issues.redhat.com//browse/OSD-13089)
=> Updates the validation controller OU logic

hack/olm-registry/olm-artifacts-template.yaml
This adds the accountpool configmap entry to the OLM template so that it can be configured via app-interface.
Ref [OSD-13614](https://issues.redhat.com//browse/OSD-13614)
=> Adds accountpool configmap entry to olm template

api/v1alpha1/account_types.go, api/v1alpha1/accountclaim_types.go, api/v1alpha1/zz_generated.openapi.go, config/config.go, controllers/accountclaim/accountclaim_controller.go, controllers/accountclaim/accountclaim_controller_test.go, controllers/accountpool/accountpool_controller.go, controllers/accountpool/accountpool_controller_test.go, deploy/crds/aws.managed.openshift.io_accountclaims.yaml, deploy/crds/aws.managed.openshift.io_accounts.yaml, hack/scripts/set_operator_configmap.sh, hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
- Add handling to AAO for multiple account pools.
- Account claims can now specify which account pool they would like to claim from, if none specified, will claim from default account pool.
Ticket ref: [OSD-13614](https://issues.redhat.com//browse/OSD-13614)
=> [OSD-13614] Add multiple accountpools to AAO

controllers/accountclaim/accountclaim_controller.go
OSD Ref: https://issues.redhat.com/browse/OSD-13614
Improving logging to understand why we're not able to claim accounts from the accountpool
=> Update logging in accountclaiming to improve accountpool issue visibility

hack/olm-registry/olm-artifacts-template.yaml
Adding `route53:ListHostedZonesByVPC` statement to `network-mgmt` role's policy.
[OSD-15530](https://issues.redhat.com/browse/OSD-15530)
=> Add route53:ListHostedZonesByVPC to network-mgmt role

docs/1.1-InstallationPrerequisites.md, docs/2.0-Development.md
The old documentation still specified v0.16.0 or < 0.18.0, however AAO can now run with operator-sdk v1.
Just fixes the documentation.
=> Update required operator-sdk version.

fips.go, hack/olm-registry/olm-artifacts-template.yaml
Feature : Adding AMI for enabling ap-southeast-4 , Melbourne
Ref OSD-0000
=> OSD-14723: Adding AMI for enabling ap-southeast-4

api/v1alpha1/shared_types.go, controllers/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, controllers/awsfederatedaccountaccess/awsfederatedaccountaccess_controller_test.go, controllers/awsfederatedrole/awsfederatedrole_controller.go, controllers/awsfederatedrole/awsfederatedrole_controller_test.go, pkg/awsclient/client.go, pkg/awsclient/mock/zz_generated.mock_client.go, pkg/utils/utils.go, pkg/utils/utils_test.go
When an `awsfederatedaccountrole` CR is updated, this change will pick up that change and sync it to all `awsfederatedaccountaccess` IAM policies for that role.
1. Create a new `awsfederatedrole` CR and `awsfederatedaccountaccess` CR for that role.
1. Check the AWS console for the account you're working with - validate that IAM policy created matches the federated role CR.
1. `oc edit` the `awsfederatedrole` you created to change the permissions in `.spec.awsCustomPolicy.awsStatements.action`.
1. Refresh your AWS console. Observe that the change made to the CR in the previous step is reflected in the IAM policy.
Ref [OSD-15564](https://issues.redhat.com//browse/OSD-15564)
=> When an AWSFederatedRole CR is updated, automatically update all associated AWSFederatedAccountAccess CRs

controllers/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Small miss from https://github.com/openshift/aws-account-operator/pull/751.
Catches an edge case where the `awsFederatedRole` label would not be applied to existing `awsfederatedaccountaccess` CRs.
=> Make sure to add federated role label to existing accounts if not present

build/Dockerfile.olm-registry, hack/olm-registry/olm-artifacts-template.yaml, hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Feature : Enabling ap-south-2region for cloud provider operators
Ref [OSD-14722](https://issues.redhat.com/browse/OSD-14722)
=> Enabling ap-south-2 region for cloud provider operators

hack/olm-registry/olm-artifacts-template.yaml, hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
This adds the eu-central-2 AMI and instance type configuration.
Ref [SDE-2273](https://issues.redhat.com//browse/SDE-2273) and [OSD-14721](https://issues.redhat.com/browse/OSD-14721)
=> [SDE-2273] Enable eu-central-2

controllers/account/account_controller.go, controllers/account/account_controller_test.go
This PR fixes the Long standing issue where some aws accounts never leave the 'Creating' state. 
Ref [OSD-16603](https://issues.redhat.com//browse/OSD-16603)
=> [OSD-16603] Fix AWS Account Creation bug

controllers/accountclaim/accountclaim_controller.go, controllers/accountclaim/accountclaim_controller_test.go
Add a check to the account cr deletion step to ensure that we only run the account cleanup when there are no additional finalizers present on the accountclaim.
Ref [OSD-19093](https://issues.redhat.com//browse/OSD-19093)
=> [OSD-19093] Don't run account claim cleanup when there are additional finalizers

controllers/validation/accountpool_validation_controller.go, hack/olm-registry/olm-artifacts-template.yaml, hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl, pkg/utils/clientwrapper.go
Adds Max Concurrent Reconcile limit field in the configmap for the accountpool validation controller
Ref [OSD-14200](https://issues.redhat.com//browse/OSD-14200)
=> OSD-14200 Add Max Concurrent Reconcile limit

controllers/accountclaim/accountclaim_controller.go, controllers/accountclaim/accountclaim_controller_test.go, controllers/accountclaim/reuse.go
Update the account cleanup process to use OrgAccessRole instead of static creds. 
=> [OSD-19300] update account cleanup

hack/olm-registry/olm-artifacts-template.yaml
Adds required field to the feature flag accountcliam_fleet_manger_trusted_arn
=> [OSD-19300-update-olm] Updated feature flag field

api/v1alpha1/shared_types.go, build/Dockerfile, build/Dockerfile.olm-registry, controllers/account/account_controller.go, controllers/account/account_controller_test.go
Quite often when an AWS account is created, we get the error message `AWS Organizations can't complete your request because it conflicts with another attempt to modify the same entity. Try again later.` from AWS. When that happens, the account CR status is set to `Failed` and it will never be retried again. This causes a new account CR to be created instead, needlessly bloating our accounts.
This PR makes sure, that this error is actually retryable.
First attempt at figuring out our runaway account creation. I don't think this is the root cause for linked issue, but it still causes our failed account count to inflate needlessly.
Ref [OSD-19873](https://issues.redhat.com//browse/OSD-19873)
=> [OSD-19873] Don't fail an account for a ConcurrentModificationException

controllers/validation/account_validation_controller.go, controllers/validation/account_validation_controller_test.go, hack/olm-registry/olm-artifacts-template.yaml, hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
This check - in contrast to all other checks - will only run for Failed accounts that have no AWSAccountId. If this is the case and the feature is enabled the account CR will be deleted.
This is a partial fix, as we are seeing a lot of Failed account without AWS account associated.
This makes it look like a lot of accounts are not being reused, while those are just not usable at all.
Ref [OSD-19874](https://issues.redhat.com//browse/OSD-19874)
I tested this locally by forcing an …
=> [OSD-19874] Add a new validation check to delete accounts.

api/v1alpha1/account_types.go, build/Dockerfile, build/Dockerfile.olm-registry, controllers/account/account_controller.go
An if statement is being added to the account controller to prevent reused accounts that only need their IAM user and secret recreated from going through the entire account initialization process.
Start the operator
Run "make predeploy"
Run "make create-account"
Set account.Spec.accountPool to "hs-zero-size-accountpool"
Run "make create-accountclaim-namespace"
Run "make create-fleet-accountclaim"
Observe that the IAMuser and secret is deleted
Run "make delete-fleet-accountclaim"
Observe that the IAMuser and secret is created
Run "create-accountclaim"
Observe that the account created in step 3 is claimed
=> [OSD-19300-update-IAMUser-recreation] update account init statement for reused accounts

build/Dockerfile, build/Dockerfile.olm-registry, pkg/utils/utils.go, pkg/utils/utils_suite_test.go, pkg/utils/utils_test.go
- Change the way missing accountpool keys in the configmap are treated
- Now, missing accountpools will be treated like their config section was emtpy
- This ensures that we don't unneccessarily run into an error condition
Ref [OSD-20500](https://issues.redhat.com//browse/OSD-20500)
=> [OSD-20500] Dont fail when pool is missing in configmap

api/v1alpha1/account_types.go, controllers/account/account_controller.go, controllers/account/region_enablement.go, controllers/validation/account_validation_controller.go
A fix to handle accounts that don't have the correct permissions to enable opt in regions. The change will update the state from TODO to MANUL_ACTION and prevent accounts from continuously trying to enable accounts with the wrong permissions 
2. Modify OrganizationAccountAccessRole permissions
3. Run "make predeploy"
4. Set "feature.opt_in_regions" to true in hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
5. Add "opt-in-regions" entry to hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
6. Run "make create-account"
7. Set account.Spec.accountPool to "hs-zero-size-accountpool"
8. Verify account CR state changes to READY
9. Verify in the AWS console that the opt-in regions specified in the configMap are enabled
Ref …
=> [OSD-21097-handle-permissions-errors] Handle Misconfigured Role Permissions

OWNERS
Dan and I are managers now on ARO and no longer need or should have ownership.
=> Remove Dan and George from OWNERS

build/Dockerfile, build/Dockerfile.olm-registry, controllers/account/ec2.go, controllers/account/ec2_test.go
Currently, when a region is being initialized, if we fail to lookup an AMI to use, or the instance type, the code would continue to execute and later fail on passing an empty string to AWS.
The function performing the initialization does return errors as well, but they are never read by the controller calling. Instead it spawns a goroutine for each region init, and uses channels to handle errors and info messages.
In the scenario where the AMI lookup fails, the error is sent back on the errors channel, and then that channel is closed, following by the goroutine continuing to run in the background until it eventually panics trying to send to the now closed error channel.
This causes the operator process to exit prematurely, leading to odd scenarios around cleaning up initialization VPCs …
=> OSD-18390: Ensure Region Initialization Fails on Missing AMI

build/Dockerfile, build/Dockerfile.olm-registry
Bumping `ubi-minimal` to pull in CVE fixes for `libxml`
Ref OSD-0000
=> OSD-28732: Bump ubi image to pull in libxml fixes

deploy/operator.yaml
Added CPU and Memory limits for the aws-account-operator.
In order to choose the values I went into a hive cluster and check the CPU and memory metrics of the operator over a period of time of weeks. The values chosen are larger than the ones showed in the metrics just in case.
Once the PR is merge into staging environment. we can deploy A cluster in stage environment and watch how to aws-account-operator handles the creation of a new cluster and seeing any spikes or metrics that appear in order to know for sure the values chosen are good.
Ref [OSD-28574](https://issues.redhat.com//browse/OSD-28574)
=> OSD-28574 enforce cpu and memory limits for aws account operator

build/Dockerfile.olm-registry
In order to resolve `GHSA-hcg3-q754-cr77` we need to bump the `ose-operator-registry` image to a newer version. However, the image we were using is an older one and the OLM team suggested moving to this one.
Additionally, the new one is rhel9, so we had to bump to `ubi9` as well. I verified with @sam-nguyen7 that `ubi9` is FIPS compliant as well, which has come up in the past. https://redhat-internal.slack.com/archives/CCX9DB894/p1738943003295999
The intent of this PR is to ensure this works in stage, and then apply the same change to `boilerplate` instead.
```
 docker build -f build/Dockerfile.olm-registry -t aws-account-operator-registry .
[+] Building 8.4s (17/17) FINISHED …
```
=> OSD-29696: Bump `Dockerfile.olm-registry` to newer images for CVE fixes

controllers/accountclaim/accountclaim_controller.go, main.go
In order to find the bug mentioned in [SREP-1631](https://issues.redhat.com/browse/SREP-1631). Additional log statements were added to the accountclaim controller
1.  Set DEBUG_LOGGING=true
2. Start the operator
3.  Observe `reqLogger.V(1).Info()` msg prints to console
Ref [SREP-1631](https://issues.redhat.com//browse/SREP-1631)
=> SREP-1631increase logging in accountclaim controller

build/Dockerfile, build/Dockerfile.olm-registry, hack/olm-registry/olm-artifacts-template.yaml
The environment variable DEBUG_LOGGING is being added to the OLM template. 
Ref [SREP-1631](https://issues.redhat.com/browse/SREP-1631)
=> SREP-1631- add DEBUG_LOGGING env var to OLM template
