- pkg/apis/aws/v1alpha1/account_types.go
- pkg/controller/account/account_controller.go
This PR fixes the return of the getSTSCredentials function and adds the spec and state details of the Account_type.
> Add account type details and bugfix

- pkg/apis/aws/v1alpha1/accountpool_types.go
- pkg/controller/accountpool/accountpool_controller.go
Define the AccountPool spec and implement the AccountPool controller.
> Implement AccountPool controller

- pkg/controller/accountpool/accountpool_controller.go
Fixed errors in accountpool_controller.go that caused compilation errors.
> Fixed errors in accountpool_controller.go that caused compilation errors

- deploy/crds/aws_v1alpha1_accountpool_cr.yaml
> Fix accountpool CR

- pkg/apis/aws/v1alpha1/accountpool_types.go
- pkg/controller/accountpool/accountpool_controller.go
> Change type of poolsize from string to int

- pkg/controller/accountpool/accountpool_controller.go
This PR handles counting the unclaimed and claimed accounts and updating the status if it not up to date.
> Fix logic for AccountPool controller to update the status of the CR

- pkg/controller/accountpool/accountpool_controller.go
Move the long if check for AccountPool status update to a function
> Refactor pool status check into a function

- pkg/controller/accountpool/accountpool_controller.go
Changing libra-ops to osd-cred-mgmt
> Update account naming scheme

- pkg/apis/aws/v1alpha1/accountclaim_types.go
This PR updates the account claim types
> Update account claim types

- pkg/controller/account/account_controller.go
This PR adds functionality to pull the aws credentials from a secret and removed debugging lines and comments
> Added pulling aws creds from secret and removed debugging lines 

- deploy/crds/aws_v1alpha1_account_crd.yaml
This PR adds information to print state and claimed on cli using oc or kubectl for the account crds.
> Added printing details to account crd

- deploy/crds/aws_v1alpha1_accountpool_crd.yaml
Example output
```
$ oc get accountpool
NAME                  POOL SIZE   UNCLAIMED ACCOUNTS   CLAIMED ACCOUNTS
example-accountpool   1           1                    0
```
> Add data to the crds so oc get can see more

- pkg/controller/account/account_controller.go
This PR fixes the error returns when updating status so that account can go into a failed state.  It also moves some of the logic out of the reconciler function to make reading the account controller cleaner.
> Refactored code and fixed error returning bugs

- cmd/manager/main.go
- deploy/operator.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
Used the documentation from [0] to enable cluster-scoping for operator.
[0] https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#operator-scope
> Enable cluster-scoping for operator

- pkg/awsclient/client.go
- pkg/controller/account/account_controller.go
This PR add the functionality of creating and terminating a EC2 instance.
> Added EC2 building and termination

- deploy/crds/aws_v1alpha1_account_crd.yaml
- deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
- deploy/crds/aws_v1alpha1_accountpool_cr.yaml
- deploy/crds/aws_v1alpha1_accountpool_crd.yaml
- pkg/apis/aws/v1alpha1/account_types.go
- pkg/apis/aws/v1alpha1/accountclaim_types.go
- pkg/apis/aws/v1alpha1/accountpool_types.go
- pkg/apis/aws/v1alpha1/zz_generated.openapi.go
- pkg/controller/accountclaim/accountclaim_controller.go
This grabs the secret holding the IAM info referenced by the account, and creates a secret with the same data with the name and namespace UHC expects via the accountclaim CR.
WIP because the code is untested
> Copy secret referenced by Account to secret that UHC expects

- config/templates/aws-account-operator-csv-template.yaml
- deploy/operator.yaml
- hack/app_sre_build_deploy.sh
- hack/app_sre_create_image_catalog.sh
- hack/app_sre_pr_check.sh
- hack/generate-operator-bundle.py
- hack/olm-registry/olm-artifacts-template.yaml
This PR adds the required scripts to deploy this operator via the APP-SRE pipeline.
> Add deploy scripts

- config/templates/aws-account-operator-csv-template.yaml
This PR fixes attributes with duplicate words (typos)
> Duplicate word

- pkg/metrics/metrics.go
This PR adds the total number of accounts to the metrics pkg .
> Added account total to metrics

- pkg/apis/aws/v1alpha1/account_types.go
- pkg/controller/account/account_controller.go
- pkg/controller/utils/conditions.go
This PR creates the scaffolding for using conditions in the account controller.
> Implemented conditions for account controller

- deploy/uhc_cluster_role.yaml
- deploy/uhc_cluster_role_binding.yaml
- deploy/uhc_service_account.yaml
This PR fixes an issue where the manifests should not be a list
> Don't use Yaml list

- pkg/controller/account/account_controller.go
> Updated AWS secret name

- pkg/controller/account/account_controller.go
This PR updates account conditions before updating the status in the account controller.
> Update conditions before updating status

- pkg/controller/account/account_controller.go
This pr makes the account states failed when returning and error from the reconcile loop
> Added failures anywhere we could return an error

- pkg/controller/account/account_controller.go
This PR sets the account creation to failed if the creation has been pending for 10 minutes or longer.
> Added creation failure if hung for 10 minutes

- deploy/crds/aws_v1alpha1_account_crd.yaml
This PR fixes a capitalization error within the account CRD effecting the status output.
> Fix account status jsonpath

- pkg/awsclient/client.go
- pkg/controller/account/account_controller.go
This PR adds the attachment of admin policy to the IAM users that are created for an account.
> Added admin policy attachment to IAM user

- pkg/controller/accountpool/accountpool_controller.go
The PR updates the AWS account email address
> Update AWS account email address

- OWNERS
This PR updates the owners file with relevant approvers and reviewers
> Updating owners file

- cmd/manager/main.go
- pkg/metrics/service.go
This PR refactors service monitor generation to redeploy the services if they already exist.
> Refactored service generation to check error

- pkg/controller/account/account_controller.go
This PR fixes a typo is the function name
> Fix typo in function name

- pkg/controller/account/account_controller.go
This PR bumps the AWS account limit
> Bump AWS account limit

- pkg/controller/account/account_controller.go
This PR bumps the account limit
> Bump account limit

- pkg/controller/account/account_controller.go
This PR make sure that we also log the AWS error message if there is an error creating a support case.
> Log AWS error message

- pkg/metrics/metrics.go
Adding `aws_account_operator_total_aws_account_pending_verification` metric to the operator
> SREP-1751 - Expose metric with total of accounts in PendingVerification

- pkg/localmetrics/localmetrics.go
Added metric for reporting on the number of accounts CRs in the "Ready" state
> Added metric for number of ready account CRs

- pkg/controller/account/account_controller.go
Fix for https://jira.coreos.com/browse/SREP-1698
Tested with: @rafael-azevedo
> Fix for pending verification bug: SREP-1698

- pkg/controller/account/account_controller.go
Increase account limit to 3000
> Increase account limit

- pkg/controller/account/account_controller.go
Reverts openshift/aws-account-operator#94
The condition on this PR doesn't appear to be catching the error "OptInRequired" as the operator is failing to create AWS accounts and logging the error:
```
{"level":"error","ts":1563827378.8574395,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"account-controller","request":"aws-account-operator/osd-creds-mgmt-dnpwrq","error":"OptInRequired: You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe.\n\tstatus code: 401
```
I'd like to revert this change as testing will take sometime and we are exhausting AWS accounts while this is not being caught.
> Revert "Fix for pending verification bug: SREP-1698"

- pkg/credentialwatcher/secretwatcher.go
This PR fixes a bug where we don't format the log message correctly.
> Fix error message formatting

- pkg/controller/account/account_controller.go
- pkg/controller/account/iam.go
I have been unable to replicate this part segfaulting. Adding in some protection to make sure that a nil point is not accessed.
> SREP-1792: Error if sts token output is nil

- pkg/controller/accountclaim/reuse.go
To solve issue where UHC deletes the AWS credential secret from the cluster's namespace, get the AWS credential from account secret, instead of accountClaim.
> SREP-1871 Get AWS credentials from account instead of accountClaim obj

- pkg/controller/accountclaim/accountclaim_controller.go
Change to address the issue created by some ci/integration jobs where accountClaims are created and deleted  too fast, before an account gets assigned (and the accountLink field is populated).
Only call the finalizeAccountClaim function if its accountLink is not empty, otherwise just remove the finalizer and leave reconcile loop.
Also related to https://github.com/openshift/aws-account-operator/issues/110
> SREP-1879 Skip finalizer function if accountLink is empty in accountClaim

- cmd/manager/main.go
Added the two reuse metrics to configuration section for metrics endpoints and registering
> Created endpoint/register for reuse metrics

- pkg/controller/account/account_controller.go
- pkg/controller/account/ec2.go
Previous logic for the createEC2Instance function was flawed. This is a revision of that code.
@rafael-azevedo @rogbas @jharrington22
> Fix for pending verification bug: SREP-1797

- pkg/controller/account/ec2.go
This PR attempts to fix an issue where we attempt to access an empty slice when we have an error.
> Check length on instance slice before assigning

- OWNERS
> Added Nina Taneja as a reviewer

- deploy/crds/aws_v1alpha1_account_crd.yaml
This PR fixes bad indentation in the account CRD.
> Fix account CRD indentation

- deploy/crds/aws_v1alpha1_account_crd.yaml
- pkg/apis/aws/v1alpha1/account_types.go
Not sure if we need to or should regen CRDs, maybe in another PR.
> Small capitalization fix

- pkg/localmetrics/localmetrics.go
Fix Ready accounts metrics, is was being left as zero.
> SREP-1987 Fix Ready accounts metric

- pkg/controller/account/account_controller.go
> SREP-1989 Bump limit to 4450

- pkg/controller/account/account_controller.go
This PR will add logic to kip creating an aws account if `.Spec.AwsAccountID` already exists. This is to support reusing failed accounts.
> Don't create account if AwsAccountID exists

- pkg/awsclient/client.go
- pkg/controller/accountclaim/reuse.go
This adds functionality to delete objects in a bucket if the bucket is not empty. Still requires testing.
> Added logic to delete bucket objects

- pkg/controller/accountclaim/reuse.go
This adds error handling for ignoring ErrCodeNoSuchBucket when reusing accounts and cleaning buckets.
> Added better error handling reuse.go

- README.md
Going through the README I saw a few readability / spelling errors.
> Spelling and readability changes to README

- pkg/controller/accountclaim/reuse.go
This PR fixes an issue were we exit a function closing message channels while go routines using those channels are still running. I've also removed unnecessary logging from those functions since we'll print any errors that arrive on the channel.
> Wait for all routines to finish, don't log errors twice

- Gopkg.lock
- pkg/controller/accountpool/accountpool_controller_test.go
Create tests for helper functions and reconcile loop in the accountpool controller.
> SREP-1979 Implement unit tests for accountpool controller

- pkg/controller/account/account_controller.go
Found one instance in setStatusFailed where status error was not being checked when updating account status
> SREP-1964 Check status error when updating account status

- hack/validate_yaml.py
This PR adds support for yaml files containing multiple yaml documents.
> Added support for yaml files with multiple documents

- pkg/controller/account/account_controller.go
Bump so hive-int can get going
> account bump for integration to work

- pkg/controller/account/account_controller.go
> Account limit bump

- pkg/localmetrics/localmetrics.go
Create a separate function for the unclaimed metric to ensure accurate reporting.
> Refactor unclaimed account metric

- pkg/controller/account/account_controller.go
> Bump account limit to 4700

- deploy/uhc_cluster_role.yaml
> added update configmaps permission to UHC cluster role

- hack/validate_yaml.py
This PR reverts safe load function in validate_yaml script.
> Reverted yaml load function to safe_load

- deploy/crds/aws_v1alpha1_awsfederatedrole_customeradmin_cr.yaml
`resource` in the Custom Policy should be an array instead of a single value.
> AWSFederatedRole CR Typo fix

- deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
- deploy/crds/aws_v1alpha1_awsfederatedrole_crd.yaml
- deploy/crds/aws_v1alpha1_awsfederatedrole_customeradmin_cr.yaml
- deploy/crds/aws_v1alpha1_awsfederatedrole_readonly_cr.yaml
- pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
- pkg/awsclient/client.go
- pkg/awsclient/mock/mock_client.go
- pkg/controller/add_awsfederatedaccountaccess.go
- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
- pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
- pkg/controller/utils/conditions.go
- pkg/controller/utils/utils.go
This PR adds basic MVP logic for the AWS Federeated Access self service.
> MVP for AWSFederatedAccountAccess controller 

- deploy/crds/aws_v1alpha1_account_crd.yaml
- pkg/apis/aws/v1alpha1/account_types.go
- pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Adding a BYOC boolean to support byoc account controller logic.
> Add BYOC field to account spec

- pkg/controller/account/account_controller.go
- pkg/controller/account/ec2.go
Re-pull request from https://github.com/openshift/aws-account-operator/pull/102
> Expand aws api errors

- pkg/controller/account/account_controller.go
- pkg/controller/account/ec2.go
- pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
- pkg/controller/utils/utils.go
Create LogAwsError function in utils to consolidate code.
> Refactor aws errors

- pkg/controller/account/account_controller.go
> Remove early success message in IAM account creation

- pkg/controller/account/credentials_rotator.go
This PR fixes an issue where is the CLI or Console STS secret doesn't exist we'll just create it (since they are temporary anyway)
cc @fahlmant
> Ignore if the STS secret doesn't exist

- deploy/crds/aws_v1alpha1_account_crd.yaml
- deploy/crds/aws_v1alpha1_accountclaim_crd.yaml
- deploy/crds/aws_v1alpha1_accountpool_crd.yaml
- deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_crd.yaml
- deploy/crds/aws_v1alpha1_awsfederatedrole_crd.yaml
- pkg/apis/aws/v1alpha1/account_types.go
- pkg/apis/aws/v1alpha1/accountclaim_types.go
- pkg/apis/aws/v1alpha1/accountpool_types.go
- pkg/apis/aws/v1alpha1/awsfederatedaccountaccess_types.go
- pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
This PR adds annotations so that the additional printer columns are generated with openapi
> Add additional printer column annotations

- config/templates/aws-account-operator-csv-template.yaml
- deploy/cluster_role.yaml
- hack/generate-operator-bundle.py
Currently CRDs are not added into the CSV, this automates that process.
> Automatically generate CRDs in CSV

- hack/generate-operator-bundle.py
This PR adds the missing name field for the CRD configuration in the CSV.
> Add CRD name

- pkg/controller/account/account_controller.go
- pkg/controller/account/byoc.go
The account controller is cluttered, so this PR works to refactor the initialization of a BYOC account into small functions in the `byoc.go` file.
> Refactor BYOC init to smaller functions 

- pkg/controller/account/account_controller.go
- pkg/controller/account/byoc.go
This PR adds more graceful handling of BYOC related errors in the account controller. Specifically, it 1) Validates that all the required fields for BYOC are present in the AccountClaim spec before continuing
2) Writes BYOC related errors to the associated AccountClaim
> Propagate BYOC account errors to accountclaim

- pkg/controller/account/account_controller.go
This PR fixes an issue where the account CR enters the "Creating" status and we never attempt to initialize the account where eventually it would set to "Ready". Since we don't ever initialize the account we assume this account is stuck "Creating" and fail it causing an AWS account leak. No account could ever become "Ready" in this state.
I also remove references to `awsAccountID`  where not required and only initialize it inside the condition where it is used and not at the pkg scope.
> Initialize account when creating, use spec AWS account ID

- pkg/controller/account/account_controller.go
Updating AWS support message reflecting vCPU usage as a limit for regions.
> Update AWS support message

- deploy/uhc_cluster_role.yaml
This PR allows the OCM service account and SDA access to federated user resources
> Allow OCM access to federated user resources

- pkg/controller/account/account_controller.go
Currently, every time a BYOC account is reconciled, an aws client is build based on the credentials in the secret referenced in the CR. This client is only used when first initializing the BYOC account and is never used again. This PR ensures that we only build the client when needed.
> Only build BYOC aws client if needed

- .gitignore
- cmd/manager/main.go
- pkg/controller/account/account_controller.go
- pkg/controller/account/credentials_rotator.go
- pkg/credentialwatcher/secretwatcher.go
Reverts openshift/aws-account-operator#249
> Revert "Rotate credentials by accounts that are in Ready state"

- pkg/controller/account/account_controller.go
Once the osdManagedAdminSRE user is created we immediately attempt to create and then use a secret containing the IAM credentials to connect to AWS. This secret is not available immediately, we need to wait. 
The correct way to implement this would be with a watch, I'll create a card to come back and refactor this as a watch.
> Wait for secret to be ready for AWSClient

- pkg/controller/account/account_controller.go
The AWS IAM SDK returns an err `InvalidClientTokenId` on first call to iam.CreateUser the second call then return that the user exists. We are attempting to handle these errors.
> Handle create IAM user call not succeeding but not return correctly

- pkg/controller/account/account_controller.go
- pkg/controller/account/iam.go
BuildIAMUser in the account controller fails if there are 2 access keys for a given user, or a secret for that user/key already exists. This PR refactors BuildIAMUser to do the following:
1) If user already exists, do not error
2) If the secret does not exist, deletes all current access keys, creates a new one, and creates a new secret with the access key.
3) If the secret does exist, assumes the key in it is usable
> Refactor BuildIAMUser and related functions

- OWNERS
Adding @fahlmant as approver :smile:
> Add fahlmant as approver

- pkg/controller/account/account_controller.go
Also edits the constants to use CONSTANT case for clarity.
Still needs to be tested locally, I'm working to set up my environment now.
> Changes random strings to use constants

- pkg/controller/account/account_controller.go
This was originally "Creating" but in #255 was mistakenly changed to "Ready".
> Fix wrong condition

- OWNERS
> Add Kirk to OWNERS

- pkg/controller/account/account_controller.go
- pkg/controller/account/ec2.go
- pkg/controller/utils/utils.go
https://issues.redhat.com/browse/OSD-1962
> Standardize the different timeouts in the operator

- pkg/controller/account/account_controller.go
- pkg/controller/account/iam.go
This deletes secrets when the corresponding account is deleted.
> Sets owner ref's on secrets

- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Found a bug where if the AWS Federated Account Access CR fails before its able to create the role in the target account, then the finalize code looped forever. This PR fixes it by returning from the role cleanup code if the role doesn't exist.
> Fix bug where missing role causes finalizer inifinite loop

- deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
- deploy/crds/aws_v1alpha1_awsfederatedrole_readonly_cr.yaml
Fixing Role CRs to match what's in the mockup. 
https://marvelapp.com/d780h9h/screen/64100971
> Fix network mgmt cr and add proper descriptions

- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
Fixes small typo in error message
> Fix typo in error message

- build/Dockerfile
Fixes the dockerfile for the multi-stage build issue with Prow.
> Dockerfile fix

- pkg/apis/aws/v1alpha1/awsfederatedrole_types.go
Removing unused constant. Tested.
> Remove unused state constant

- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
We currently have code that is supposed to handle if a Policy or Role already exists by using the AWS Error code EntityAlreadyExists. However, the functions that were supposed to return this error were returning another non-AWS error. 
In order to fix these, each FAA with get a unique UUID appended as a label at creation time. Then every role and policy created will get that uuid appended to the end of the name during creation and deletion actions.
> Fix bug where using same role in account with second user fails

- pkg/controller/account/iam.go
This PR fixes a small typo in the error message.
> Fix small typo in error message

- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
This change handles errors that do not fall under the `awserr.Error`
type, and ensures they are returned if encountered, and not dropped.
> Handles non-AWS errors returned by createIAMRole function

- deploy/uhc_service_account.yaml
The namespace on the UHC service account is incorrect.
> Fix namespace on SA

- OWNERS
Adds clcollins to the list of reviewers
> Adds clcollins to reviewers

- deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
https://issues.redhat.com/browse/OSD-3134
> Removes support:* from FederatedAccessRole

- pkg/credentialwatcher/secretwatcher.go
This PR has secretwatcher run on startup and logs if there are any errors. Once that is complete secretwatcher runs as normal every 10 minutes
> Secret watcher run on startup

- README.md
- cmd/manager/main.go
- pkg/controller/account/account_controller.go
- pkg/controller/utils/utils.go
I took @rafael-azevedo's PR on Local Dev Mode and ran with it to fix the other points in the code that need to get modified for local testing.
> Local dev mode

- pkg/controller/account/account_controller.go
- pkg/controller/account/account_finalizer.go
- pkg/controller/accountclaim/accountclaim_controller.go
- pkg/controller/accountclaim/accountclaim_finalizer.go
- pkg/controller/utils/utils_test.go
Refactors Finalizers to their own files.
Tested by creating a BYOC accountclaim and by creating an account and accountclaim.
> Finalizer refactor

- Makefile
- hack/templates/aws_v1alpha1_accountclaim_cr.tmpl
The PR adds a `test-reuse` make target to test AWS account reuse.
> Add reuse test make target

- README.md
This PR includes multiple minor fixes to the README.md file, including:
* remove trailing whitespace
* updates TOC with new sections
* fixes heading levels
* adds code type tags to code blogs
> Fixes formatting and syntax issues in the README.md

- Makefile
This PR replaces a lot of hard-coded strings with variables and removes
an unnecessary `grep` within the Makefile.
> Replaces hard-coded data with variables; simplifies some piped commands in Makefile

- Makefile
- hack/scripts/test_envs
- test/integration/api/create_account.sh
- test/integration/api/delete_account.sh
- test/integration/api/delete_account_secrets.sh
This PR removes duplicated make targets and moves them into scripts. It also introduces a test directory where we will later add Go integration tests replacing these bash scripts.
> Test scripts

- Makefile
- pkg/controller/account/account_controller.go
- pkg/controller/account/account_controller_test.go
- pkg/controller/account/byoc.go
- pkg/controller/account/byoc_test.go
This change moves some simple checks and complex logic to functions that
return boolean results for the different possible states of the account,
allowing more testable checks readable code.
Also includes tests for the new functions to validate they are returning
the correct output given the expected account input.
> Moves complex logic and simple checks to function that return boolean results

- hack/scripts/aws/rotate_iam_access_keys.sh
This PR fixes the rotate access keys script which put mixed up the base64 output.
> Fix secret output

- hack/scripts/aws/rotate_iam_access_keys.sh
This PR adds the new base64 output to the kubernetes secret that is generated.
> Fix kubernetes secret output

- pkg/controller/account/iam.go
We're missing a lot of documentation and specifics for functions in the `iam.go` file. This PR adds descriptions and basic list of arguments for each function.
> Add documentation for functions in iam.go

- deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
In accordance with https://docs.openshift.com/dedicated/4/cloud_infrastructure_access/dedicated-aws-vpn.html#dedicated-aws-vpn-creating-configuring
The ec2:CreateCustomerGateway has been added to this policy CR
> Added CreateCustomerGateway perm

- pkg/controller/account/account_controller.go
- pkg/controller/account/credentials_rotator.go
- pkg/controller/account/iam.go
- pkg/controller/account/secrets.go
- pkg/controller/account/secrets_test.go
Abstracts away the Secrets creation logic into a separate function.
> Create function for SecretsCreator

- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
This PR moves the AWS Federated Account Access finalizer cleanup to use the root account (aws-account-operator-credentials) access keys to assume the `OrganizationAccountAccessRole` in the target AWS account rather than the secret specified in the CR. This solves an issue where the secret is deleted and the AFAA finalizer can't complete properly and leaves extra Federated Roles.
> Use root account creds to assume a role in target account for federated role cleanup

- standard.mk
This PR adds a make target to generate code specifically the awsclient mock
> Add generate target to generate code, mocks etc

- pkg/apis/aws/v1alpha1/shared_types.go
- pkg/controller/account/ec2.go
`var ResourceType = "ec2Resource"` was not a valid resource type to tag
> fix ec2 tag resource type name

- pkg/controller/account/iam.go
This PR fixes a few comments to ensure compatibility with Godoc standards.
> Ensures godoc compatibility with iam.go

- pkg/awsclient/tags.go
- pkg/controller/account/account_controller.go
- pkg/controller/account/ec2.go
- pkg/controller/account/iam.go
- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
- pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
- pkg/localmetrics/localmetrics.go
- pkg/totalaccountwatcher/totalaccountwatcher.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Fix some typos.
> Fix some typos

- pkg/controller/accountclaim/accountclaim_controller.go
> Fixes small typo in accountclaim_controller.go

- deploy/crds/aws_v1alpha1_awsfederatedaccountaccess_cr.yaml
Signed-off-by: yeya24 <yb532204897@gmail.com>
> Update outdated awsfederatedaccountaccess example

- pkg/controller/account/credentials_rotator.go
Fixes another instance of secret key values that were not fixed during an old refactor.
> Fixes broken secret keys from old refactor

- README.md
This adds documentation for the AWSFederatedRole and AWSFederatedAccountAccess CRs
> Updated README with documentation on the AWSFederated* CRs

- Makefile
> OSD-4181: Unify PHONY targets

- pkg/controller/accountclaim/organizational_units.go
Look for the `LegalEntity ID` inside the `AccountClaim CR` instead of the `Account CR`.
[Ticket](https://issues.redhat.com/browse/OSD-4015)
> Fix for the InvalidParemeter OU error

- README.md
Adding the configmap and explanations about its values to the README
> Add config map to the README

- pkg/controller/account/account_controller.go
- pkg/controller/accountclaim/accountclaim_controller.go
> Adds logging for account creation debugging

- pkg/controller/account/byoc.go
This fixes a bug that prevents a failure to create the BYOCAdminAccess role from immediately returning, logging and restarting the reconcile loop for CCS accounts. Previously, if the creation of the role failed, the CCS initialization would just continue on.
This also fixes condition messages for the CCS accountClaims, so that they are updated as errors occur, as opposed to keeping the same error message no matter what.  This prevented OCM/users from seeing the actual error message causing their CCS account to fail.
This is a direct impact on https://issues.redhat.com/browse/OSD-3978 "report more granular status for OCM", allowing the failure to surface, and repeated errors to be reported (updating the condition, as opposed to leaving it as failed with the original message). …
> Fixes bug preventing BYOCAdminAccess role creating failure from causing an immediate reconcile; condition update for accountClaim

- pkg/apis/aws/v1alpha1/shared_types.go
- pkg/controller/accountclaim/accountclaim_controller.go
- pkg/controller/accountclaim/organizational_units.go
**Card**: https://issues.redhat.com/browse/OSD-4494
**Test**: None, hard to test and there's no need to IMO
This is a fix to the ConcurrentModificationException (caused by race a condition) error that we've been seeing due to two stage environments.
> Edge case fix for ConcurrentModificationException OU error

- pkg/apis/aws/v1alpha1/shared_types.go
- pkg/controller/account/account_controller.go
- pkg/totalaccountwatcher/totalaccountwatcher.go
Adds a very high value for the intial account count so that we stop creating accounts on initialization failures.
> Adds a default value for current accounts.

- deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
This PR begins to add the targeted AWS Statements based on the Customer Facing documentation.
> Adds Permissions for creating a VPN

- deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
Should be merged after the DirectConnect (#391) and VPN (#390) PRs.
> Adds VPC Peering Permissions

- pkg/controller/accountclaim/accountclaim_controller_test.go
Previously these tests were making real AWS calls (but not failing because the errors weren't percolating up).
This commit just mocks the AWS client so we're no longer making those calls. A future commit ought to make proper use of the mocks to `EXPECT()` calls appropriately, etc.
> Mock AWS client in accountclaim_controller tests

- pkg/awsclient/client.go
- pkg/controller/account/account_controller.go
- pkg/controller/accountclaim/accountclaim_controller.go
- pkg/controller/accountclaim/accountclaim_controller_test.go
- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
- pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
- pkg/totalaccountwatcher/totalaccountwatcher.go
...following [review comments from #423](https://github.com/openshift/aws-account-operator/pull/423#discussion_r462472137)
> Rename: Builder => IBuilder; RealBuilder => Builder

- Makefile
- hack/scripts/set_operator_credentials.sh
- hack/templates/aws_v1alpha1_aws_account_operator_credentials.tmpl
Adds a quick script to change the AWS account operator credentials based on an AWS profile in your credentials file.
> Quick Operator Credentials Change

- hack/olm-registry/olm-artifacts-template.yaml
Add AccountPool CR to the template used by CICD, having parameters per environment to keep the accountLimit
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/7578
> Deploy accountpool cr cicd

- hack/olm-registry/olm-artifacts-template.yaml
v1 - > aws.managed.openshift.io/v1alpha1
> Fix AccountPool API version

- hack/olm-registry/olm-artifacts-template.yaml
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/7630
> fix accountpool olm template

- pkg/controller/account/ec2.go
- pkg/controller/accountpool/accountpool_controller.go
One of these will actually make it easier to trace logs. The other two I
just happened to noticed along the way.
> Trivial: typos

- hack/olm-registry/olm-artifacts-template.yaml
https://issues.redhat.com/browse/OSD-4603
> Deploy federatedroles cicd

- hack/olm-registry/olm-artifacts-template.yaml
potentially causing error while building
> fix typofix olm template

- hack/app_sre_create_image_catalog.sh
Fix catalog image script to point to the recent app-interface repo
Jira: OSD-4790
> OSD-4790 Fix Catalog Image script

- hack/olm-registry/olm-artifacts-template.yaml
Need to fix this in order to properly deploy AWSFederatedRole CR through the app-interface pipeline
> Fix olm artifacts indentation error

- Makefile
Make sure the FORCE_DEV_MODE variable is passed to operator-sdk
> OSD-4944 - Fix deploy-local make target

- pkg/controller/accountclaim/organizational_units.go
Ran into errors with nil points in line 83. This is a quick fix to ensure nothing line 83 uses is nil.
> Quick fix for OU errors

- hack/app_sre_create_image_catalog.sh
...to get around shiny new docker rate limiting problems.
> Use yq image from quay

- deploy/crds/aws_v1alpha1_awsfederatedrole_networkmgmt_cr.yaml
- test/integration/federated_access_cr_test.go
This PR adds the necessary permission to enable transit gateway self-service for DirectConnect setup.
> Adds Permission needed to add transitgateway self-service

- pkg/apis/aws/v1alpha1/account_types.go
- pkg/controller/account/account_controller.go
- pkg/controller/account/account_controller_test.go
- pkg/controller/account/byoc.go
- pkg/controller/utils/conditions.go
Moves the helper methods out of the Account Controller and BYOC files in
order to put them directly on the struct where they make more sense.
> Refactors Account Struct to have methods

- pkg/apis/aws/v1alpha1/shared_types.go
- pkg/controller/accountclaim/organizational_units.go
- pkg/controller/accountclaim/organizational_units_test.go
Make OU logic more resilient 
[Ticket](https://issues.redhat.com/browse/OSD-4822)
> Refactor ou logic

- README.md
> Clarifies environment variable setup instructions and fixes some linter issues for README.md

- pkg/controller/account/account_controller.go
Asynchronous region initialization (#454, #459) timed out 100 minutes after the Account CR was *created*. This was problematic in the following scenario:
- We're out of capacity in the config map's `account-limit`.
- The Account CR is created.
- Time passes (more than 100 minutes).
- We increase the `account-limit`.
The desired behavior is for the Account CR to be picked up and initialized. However, prior to this commit we would time it out as soon as we had transitioned it to the `InitializingRegions` state, because that immediately preceded backgrounding the region initialization, but the state transition would trigger a Reconcile.
With this commit, we:
- Measure the time the CR has been in the `InitializingRegions` state by looking at the `lastTransitionTime` of the corresponding …
> Time InitializingRegions by Condition

- pkg/controller/account/account_controller.go
Make this mostly-monolithic method into more manageable methods.
Pure refactor, no change to functionality or code paths.
> Refactor massive account controller Reconcile

- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
During the AWS Federated Account Access clean up, the OrganizationAccounAccessRole is assumed. If this fails, then currently the CR will be stuck in the finalizer forever. This means any CCS cluster with an AWS Federated Account Access will fail to clean that role. Since there's no guarantee that the Account CR is around, it cannot be relied on to see if a given cluster is CCS or default. To work around this, if assuming the OrganizationAccounAccessRole fails, the cleanup now tries to assume BYOCAdminAccess-uid role. If that works, then the cleanup continues normally. If both fail, then its assumed the cluster is a misconfigured CCS cluster.
> Try and assume BYOCAdminAcccess-uid role during AFAA cleanup

- pkg/awsclient/iam.go
- pkg/controller/accountclaim/organizational_units.go
- pkg/controller/accountclaim/reuse.go
Pulled these out from another PR that needs more discussion.
> Fixes linting errors

- Makefile
There were a few .PHONY targets with dots in front of their name, which made them not work from the command line and get the error "There is nothing to do"
Removed the `create-ou-map` and `delete-ou-map` from the create and delete accountclaim targets in order to allow successive tests on the same operator-local environment now that the configmap is expected to persist.
Removed the double check for ou env vars in the test-aws-ou-logic target.
There is no card, I just noticed these and wanted to fix them.
> Fixed some makefile problems

- pkg/controller/account/iam.go
This satisfies the simple solution to [osd-5610](https://issues.redhat.com/browse/osd-5610).
> Adds retry steps to other IAM components

- Makefile
Modifies Makefile to also run the go tests, in order to have a single make target that tests _all the things_.
> Actually test ALL THE THINGS

- OWNERS
Adding @lisa and @drpaneas as reviewers, and @iamkirkbater as approver.
> Update OWNERS file - approvers and reviewers lists

- hack/scripts/set_operator_credentials.sh
Fix local path reference to credential template.
> Fix credentials script path

- cmd/manager/main.go
- pkg/controller/account/account_controller.go
- pkg/totalaccountwatcher/totalaccountwatcher.go
> osd-5105 - Convert totalaccountwacther initialization to async

- README.md
Trivial update in README to add a hyperlink to docs.
PTAL
> Add a hyperlink to docs in README.

- pkg/controller/account/byoc.go
Card -> https://issues.redhat.com/browse/OSD-6386
> Prevents possible race condition while trying to access byoc secret

- pkg/awsclient/client.go
https://issues.redhat.com/browse/OSD-6759
> Add throttle and retries to aws client

- Makefile
The Makefile is already more than 300 LoC and that makes it difficult to check for the various available targets. Consequently, I created a help target to display a list of all the available targets. I used most of the current comments in the Makefile. The comments could be improved, but this can happen in another iteration.
Example output:
```shell
$ make help
Usage:
make <target>
help             Display this help
check-aws-account-id-env  Check if AWS Account Env vars are set
check-ou-mapping-configmap-env  Check if OU mapping ConfigMap Env vars are set
create-account   Create account
delete-account   Delete account
test-account-creation  Test Account creation
create-accountclaim-namespace  Create account claim namespace
delete-accountclaim-namespace  Delete account claim namespace …
```
> Added a help target in Makefile

- cmd/manager/main.go
Added messages in errors that weren't returning a meaningful message.
PTAL
> Improve failure path messages

- pkg/awsclient/client.go
- pkg/awsclient/mock/zz_generated.mock_client.go
- pkg/controller/account/ec2.go
CARD -> https://issues.redhat.com/browse/OSD-5810
> Delete hanging micro instances on account creation

- pkg/controller/account/ec2.go
Prevent erroring out from attempted account cleanup. Instead logging the error and continuing to account initialization normally.
> Fix to errors seen in stage after merge of last PR

- OWNERS
Adds Pavlos and Dan to be reviewers
> Adds Pavlos and Dan

- apis/aws/v1alpha1/accountclaim_types.go
- pkg/controller/account/byoc.go
Builds off of #519 and refactors out some accountclaim logic.  Only [this commit](https://github.com/openshift/aws-account-operator/pull/543/commits/96196f1cf2748e6bded8956d19e2a0693c65bc6b) is relevant to this PR, the others are carryover from 519
> Refactors AccountClaim Validate functions into the AccountClaim CR

- pkg/controller/accountclaim/accountclaim_controller.go
Added the BYOC account status to appear in the log message for requeuing.
PTAL
> [OSD-6788] add BYOC account status in log message

- deploy/crds/aws.managed.openshift.io_accountclaims_crd.yaml
- hack/olm-registry/olm-artifacts-template.yaml
- pkg/apis/aws/v1alpha1/accountclaim_types.go
- pkg/apis/aws/v1alpha1/zz_generated.openapi.go
Reverts openshift/aws-account-operator#564
> Revert "Adds necessary field for Support ARN"

- Makefile
- README.md
- docs/1.0-Installation.md
- hack/scripts/set_operator_configmap.sh
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
After some troubleshooting around STS, I realized that some areas need an update to reflect the latest STS changes. 
I updated the configmap generation script and the docs.
Needs #574 to be merged first
PTAL
> Improve STS related docs

- Makefile
Some CR files have been moved outside of the `crd` directory, so I updated the file paths in the Makefile to match the correct ones.
PTAL
> Fix path for CRD files

- pkg/controller/account/byoc.go
Attempting to debug https://issues.redhat.com/browse/SDA-4272 and I _think_ this is where this is failing but because the accountclaim cannot be updated because of a conflict it's failing to log the clientErr
> Adds log message to see if it's a client error

- pkg/controller/account/account_controller.go
- pkg/controller/account/account_controller_test.go
- pkg/controller/accountclaim/reuse.go
- pkg/controller/utils/utils.go
Reverts openshift/aws-account-operator#491
> Revert "Unifies CCS and Non-CCS account naming conventions"

- deploy/uhc_cluster_role_binding.yaml
* typo in namespace of ClusterRoleBinding
> Fix namespace in UHC ClusterRoleBinding

- pkg/awsclient/iam.go
We only iterate through 3 pages of IAM users, we should iterate through every IAM user.
> Iterate through all IAM users

- Makefile
- docs/1.1-InstallationPrerequisites.md
- hack/scripts/aws/sts-infra-precheck.sh
This PR adds a script to validate that your STS role arns are set up correctly by running through the assume-role steps.
> Adds script to validate sts role arn access

- pkg/controller/account/account_controller.go
- pkg/controller/account/account_controller_test.go
- pkg/controller/account/byoc.go
- pkg/controller/account/byoc_test.go
- pkg/controller/account/ec2.go
- pkg/controller/account/iam.go
- pkg/controller/accountclaim/accountclaim_controller.go
- pkg/controller/accountclaim/accountclaim_controller_test.go
- pkg/controller/accountclaim/reuse.go
- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
[OSD-6506](https://issues.redhat.com/browse/OSD-6506)
- Refactored account claim parts of finaliser into an account finaliser  
- Refactored chunks of AccountController reconcile loop into smaller functions 
- Added some unit tests
> [OSD-6506] Refactor Account Reuse Logic

- pkg/apis/aws/v1alpha1/accountclaim_types.go
- pkg/controller/utils/conditions.go
- pkg/controller/utils/utils.go
Ref : [OSD-4992](https://issues.redhat.com/browse/OSD-4992)
> [OSD-4992] Remove unused func SetBYOCAccountClaimStatusAWSAccountInUse

- pkg/controller/account/account_controller_test.go
- pkg/controller/account/iam.go
- pkg/controller/account/iam_test.go
Created a PR of some tests to expand golang testing knowledge and our test coverage for iam.go
> Improve on IAM test coverage

- Makefile
- test/integration/tests/validate_sts_accountclaim.sh
Ref: https://issues.redhat.com/browse/OSD-7432
- Renamed `test-sts-accountclaim` to `test-sts`
- Added some validation for STS mode account and account claim
> [OSD-7432] Added STS validation

- pkg/controller/account/account_controller_test.go
Just adding a test to slowly improve coverage
> Adding Test for CreateAccount in account_controller

- Makefile
Ref: https://issues.redhat.com/browse/OSD-7506
> [OSD-7506] Added reuse validation for integration test

- Makefile
- test/integration/tests/validate_ccs_accountclaim.sh
Added CCS validation step for integration tests
> Add script for validating ccs accountclaim and account

- Makefile
- hack/scripts/set_operator_configmap.sh
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
- pkg/apis/aws/v1alpha1/shared_types.go
- pkg/controller/account/account_controller.go
- pkg/controller/account/byoc.go
- pkg/controller/account/byoc_test.go
- pkg/controller/account/iam.go
- pkg/controller/account/iam_test.go
- pkg/controller/accountclaim/accountclaim_controller.go
Ref [OSD-8416](https://issues.redhat.com/browse/OSD-8416):
Added ManagedOpenShiftSupportRole to accounts and update SupportRoleARN in accountClaim with Role ARN
> [OSD-8416] Added ManagedOpenShiftSupportRole to accounts 

- pkg/controller/account/account_controller.go
- pkg/controller/account/account_finalizer.go
https://issues.redhat.com/browse/OSD-8550
> add finalizer to non-sts cr

- docs/3.1-AccountPool.md
Satisfies [OSD-7640](https://issues.redhat.com/browse/OSD-7640) and [OSD-9105](https://issues.redhat.com/browse/OSD-9105)
> Update accountpool docs

- OWNERS
Panos is no longer with the team, so I removed him from the list of reviewers.
PTAL
> Remove Panos from Reviewers

- cmd/manager/main.go
- config/config.go
- config/config_test.go
- hack/olm-registry/olm-artifacts-template.yaml
- pkg/apis/aws/v1alpha1/shared_types.go
- pkg/controller/account/account_controller.go
- pkg/controller/account/byoc.go
- pkg/controller/account/iam.go
- pkg/controller/account/iam_test.go
- pkg/controller/accountclaim/accountclaim_controller.go
- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
- pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
- pkg/totalaccountwatcher/totalaccountwatcher.go
for [OSD-6798](https://issues.redhat.com/browse/OSD-6798)
> support govcloud

- docs/2.0-Development.md
- docs/6.0-Maintenance.md
- hack/olm-registry/olm-artifacts-template.yaml
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Adds support for the new region and updates the documentation to walk
through how to add another new region in the future.
Satisfies [OSD-9890](https://issues.redhat.com/browse/OSD-9890)
> Adds support for new ap-southeast-3 region

- Makefile
- hack/scripts/aws/setup_aws_accounts.sh
- hack/scripts/aws/sts-infra-precheck.sh
- pkg/awsclient/client.go
- pkg/awsclient/mock/zz_generated.mock_client.go
- pkg/controller/accountclaim/accountclaim_controller_test.go
- pkg/controller/accountclaim/reuse.go
Cleanup VPC endpoint service configurations on reuse
jira: [OSD-10055](https://issues.redhat.com/browse/OSD-10055)
> Remove privatelink endpoints

- pkg/controller/accountclaim/reuse_test.go
* force waiting for the go routine to finish before returning the channel output
jira: [OSD-10055](https://issues.redhat.com/browse/OSD-10055)
> Add wait group to reuse tests

- cmd/manager/main.go
- hack/olm-registry/olm-artifacts-template.yaml
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
- pkg/controller/account/account_controller.go
- pkg/controller/account/iam.go
- pkg/controller/account/iam_test.go
- pkg/controller/accountclaim/accountclaim_controller.go
- pkg/controller/accountpool/accountpool_controller.go
- pkg/controller/awsfederatedaccountaccess/awsfederatedaccountaccess_controller.go
- pkg/controller/awsfederatedrole/awsfederatedrole_controller.go
- pkg/controller/utils/clientwrapper.go
- pkg/controller/utils/utils_test.go
This PR probes the osd-admin secret in accounts and heal them if they're invalid https://issues.redhat.com/browse/OSD-9298
> probe secret

- hack/olm-registry/olm-artifacts-template.yaml
Updates the olm template to use strings instead of integers.
> Fixes OLM template for configmap

- OWNERS
Adding macgregor to AAO approvers list
> Aao mstratto approvers

- Makefile
- OWNERS
- boilerplate/_lib/container-make
- hack/scripts/aws/setup_aws_accounts.sh
- hack/scripts/aws/verify-organization.sh
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
- pkg/awsclient/client.go
- pkg/awsclient/mock/zz_generated.mock_client.go
- pkg/controller/account/account_controller.go
- pkg/controller/account/account_controller_test.go
- pkg/controller/validation/account_validation_controller.go
- pkg/controller/validation/account_validation_controller_test.go
This PR includes changes from https://github.com/openshift/aws-account-operator/pull/702 and should not be merged until it's taken care of first for an accurate diff.
> Osd 10116 verify account tags

- pkg/controller/validation/account_validation_controller.go
- pkg/controller/validation/account_validation_controller_test.go
The current logic was the wrong way around.
> [OSD-9910] Validate only account pool accounts.

- pkg/controller/account/ec2_test.go
adds unit tests for functions added in #647 / [OSD-10146](https://issues.redhat.com//browse/OSD-10146)
> OSD-10398 unit tests for functions added in #647 / OSD-10146

- Makefile
- hack/scripts/cleanup-aws-resources.sh
- hack/scripts/integration-test-bootstrap.sh
EC2 instances and VPCs cleanup script after prow CI integration-test step is completed.
Jira Story:- https://issues.redhat.com/browse/OSD-12630
> [run-int-test] [OSD-12630] Add AWS Cleanup handling for prow CI

- hack/scripts/integration-test-bootstrap.sh
Integration test bootstrap script updates for local and cluster flows.
- Sanity Check added for checking:-
(1) Current Directory == Root Directory
(2) AWS credential variables are set
- backplane-cluster-admin access for staging flow.
> [run-int-test][OSD-12227] update int-test bootstrap script for local & staging

- hack/olm-registry/olm-artifacts-template.yaml
- hack/templates/aws.managed.openshift.io_v1alpha1_account.tmpl
- hack/templates/aws.managed.openshift.io_v1alpha1_accountclaim_cr.tmpl
- hack/templates/aws.managed.openshift.io_v1alpha1_aws_account_operator_credentials.tmpl
- hack/templates/aws.managed.openshift.io_v1alpha1_awsfederatedaccountaccess_cr.tmpl
- hack/templates/aws.managed.openshift.io_v1alpha1_ccs_accountclaim_cr.tmpl
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
- hack/templates/aws.managed.openshift.io_v1alpha1_fake_accountclaim_cr.tmpl
- hack/templates/aws.managed.openshift.io_v1alpha1_kms_accountclaim_cr.tmpl
- hack/templates/aws.managed.openshift.io_v1alpha1_sts_accountclaim_cr.tmpl
- hack/templates/namespace.tmpl
Update our templates to use the updated apiVersion.
> Template has a new apiVersion.

- OWNERS
Updates Ownersfile to be more current.
> Updates ownersfile to be current

- .github/pull_request_template.md
Adds a Pull Request Template to AAO.
Ref [OSD-13006](https://issues.redhat.com//browse/OSD-13006)
> Adds Pull Request Template

- OWNERS
> Updates Owners

- config/config.go
- controllers/accountclaim/accountclaim_controller.go
- controllers/accountclaim/accountclaim_controller_test.go
- controllers/accountpool/accountpool_controller.go
- controllers/accountpool/accountpool_controller_test.go
- hack/scripts/set_operator_configmap.sh
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Ref [OSD-13614](https://issues.redhat.com/browse/OSD-13614)
> [OSD-13614] AWS Account Operator supports multiple pools

- docs/8.0-ServiceQuotas.md
- docs/README.md
Adding Service Quota docs
Ref: [OSD-13615](https://issues.redhat.com//browse/OSD-13615)
> Adding service quota documentation

- hack/olm-registry/olm-artifacts-template.yaml
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Feature : Enabling me-central-1 region for cloud provider operators
Ref [OSD-14719](https://issues.redhat.com//browse/OSD-14719)
> Enable new region me-central-1 for cloud provider operators

- docs/3.4-AWSFederatedRole.md
- docs/3.5-AWSFederatedAccountAccess.md
Updated documentation
Ref [OSD-15564](https://issues.redhat.com//browse/OSD-15564)
> Update docs outlining the responsibilities of federated role and accountaccess controllers

- hack/olm-registry/olm-artifacts-template.yaml
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Add eu-south-2 and associated AMIs and instance types
Ref: [SDE-2272](https://issues.redhat.com//browse/SDE-2272)
> [SDE-2272] Add eu-south-2 and associated AMIs and instance types

- controllers/account/account_controller.go
Adds more logs to try to better track where the account creation error is happening.
Ref [OSD-16603](https://issues.redhat.com//browse/OSD-16603)
> Adds more logs to try to track down account creation error

- controllers/account/cases.go
Ref [OSD-18818](https://issues.redhat.com//browse/OSD-18818)
> Update message template for enterprise support enablement cases in AWS

- api/v1alpha1/account_types.go
- controllers/account/service_quota.go
Add EC2 Network ACL Service Quota
Ref [OSD-19281](https://issues.redhat.com//browse/OSD-19281)
> [OSD-19281] Add EC2 Network ACL Service Quota (L-2AEEBF1A)

- controllers/account/account_controller.go
- controllers/account/service_quota.go
- controllers/accountpool/accountpool_controller.go
- controllers/validation/account_validation_controller.go
- controllers/validation/accountpool_validation_controller.go
- controllers/validation/accountpool_validation_controller_test.go
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
- main.go
- pkg/utils/utils.go
Implement servicequota change/increase for an accountpool by updating the configmap
Ref [OSD-14200](https://issues.redhat.com//browse/OSD-14200)
> OSD-14200 Implement servicequota change/increase for an accountpool

- hack/olm-registry/olm-artifacts-template.yaml
Added accountpool validation feature flag to olm artifacts template
Ref OSD-0000
> [OSD-14200-update-olm-template] Updated olm artifacts template

- api/v1alpha1/account_types.go
- controllers/account/service_quota.go
Updates NetworkAclQuotaCode and GeneralPurposeSSD to use the correct service code
Ref OSD-0000
> [OSD-19281-update-service-code] Updated service code

- controllers/accountclaim/accountclaim_controller.go
- controllers/accountclaim/accountclaim_controller_test.go
- hack/olm-registry/olm-artifacts-template.yaml
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Puts [OSD-19300](https://issues.redhat.com//browse/OSD-19300) changes behind a feature flag
> [OSD-19300-add-feature-flag] Add feature flag for FleetmanagerConfig

- OWNERS
Adding myself to OWNERS file since I've been doing a lot of the reviews for this repo 😄
> Add AlexVulaj to approvers in owners file

- controllers/accountclaim/accountclaim_controller.go
- controllers/accountclaim/accountclaim_controller_test.go
- hack/olm-registry/olm-artifacts-template.yaml
- hack/templates/aws.managed.openshift.io_v1alpha1_configmap.tmpl
Fixes accountclaim feature flag typo
> [OSD-19300-fix-typo] Fix feature flag typo

- controllers/account/account_controller.go
- controllers/account/byoc.go
- controllers/account/ec2.go
- controllers/account/iam.go
- controllers/account/iam_test.go
- controllers/accountclaim/accountclaim_controller.go
- controllers/accountclaim/accountclaim_controller_test.go
Revert latest PR as it seems to break cluster creation in staging.
Ref OSD-0000
> Revert osd 19300

- Makefile
- build/Dockerfile
- build/Dockerfile.olm-registry
updated makefile comments
Ref OSD-0000
> Update makefile comments

- controllers/accountclaim/reuse.go
When attempting to cleanup s3 buckets in a different region than the default region it will fail otherwise.
Ref OSD-0000
> [OSD-20863] Must use the cluster region or s3 cleanup fails.

- build/Dockerfile
- build/Dockerfile.olm-registry
- hack/olm-registry/olm-artifacts-template.yaml
Fix field value for OLM template
Ref [OSD-21095](https://issues.redhat.com//browse/OSD-21095)
> [OSD-21095-fix-olm-template] fix olm template

- build/Dockerfile
- build/Dockerfile.olm-registry
- docs/9.0-Opt-In-Regions.md
Updated Documenatation
Ref [OSD-21099](https://issues.redhat.com//browse/OSD-21099)
> [OSD-21099] Updated opt-In region doc

- build/Dockerfile
- build/Dockerfile.olm-registry
- go.mod
> OSD-22912 Update Go Version to 1.21

- OWNERS
> Remove AlexVulaj from ownersfile

- OWNERS
Remove no longer accurate approvers / reviewers.
> Update owner files.
